### ISSUE TITLE
Are the sources for Docker for AWS public available

### ISSUE THREAD

**Issue by DanielMaier-BSI** [docker/for-aws#1]
Hi,

this is more a question than an issue. I got to this repository through the AWS for Docker documentation. I expected to see some source code here, e.g. the sources of the pre-deployed docker containers on the AMIs or how the AMI is built itself. 

Are these sources available anywhere else or is it planed to publish them?

Thanks
Daniel

**Comment by goloroden** [comment]
And, to add to this question: Is there a place where issues for *Docker for AWS* can / shall be discussed?

**Comment by friism** [comment]
@DanielMaier-BSI the source code for those containers is not currently available. We are planning to open source some of the components that go into Docker for AWS later.

@goloroden Feel free to post any issues here. We also monitor the [forums](https://forums.docker.com/c/docker-for-aws) and the Docker-for-AWS channel on the Docker Community slack: https://dockercommunity.slack.com/archives/docker-for-mac

**Comment by goloroden** [comment]
Hey @friism, thanks a lot 😊

**Comment by roundand** [comment]
Hi - I've set up Docker for AWS - which went smoothly, thank you! - and I'd like to do a pull from a private registry with an insecure domain key. But I can't see how docker is started or configured on the created EC2 boxes, so I can't work out how to add an --insecure-registry flag.

Is there any documentation on how these Swarm servers implement their docker config? Or any advice on how to add support for an insecure registry?

**Comment by kencochrane** [comment]
@roundand if you look at the cloudformation template, you will find a userdata section for the manager and the worker, in there you will see where we are creating the `/etc/docker/daemon.json` you can change the template to include your insecure-registry setting to that file, and it should work on next deploy. We will look at adding this as a config option in the future.

**Comment by roundand** [comment]
@kencochrane Thanks. I found the two sections where daemon.json was being created for manager and for nodes, added a preceding:

    "mkdir -p /etc/docker\n",

and a following:

    "echo '{' >> /etc/docker/daemon.json\n",
    "\n",								
    "echo '  \"insecure-registries\" : [\"ieartifactory.ie.com:5000\"]' >> /etc/docker/daemon.json\n",
    "\n",								
    "echo '}' >> /etc/docker/daemon.json\n",
    "\n",								

but it still doesn't work, in the sense that when I ssh into the management node there is no `/etc/docker` directory, let alone `etc/docker/daemon.json`. 

Additionally, `sudo docker info` includes the lines:

    Insecure Registries:
     127.0.0.0/8

And I can't see anywhere in the template where that value is being set.

It's quite possible that I need to learn more about AWS CloudFormation, and/or about Alpine. I think we'll come back to Docker for AWS in a few months time.

Thanks for the help, and hope you guys had a great 4th July :)

**Comment by kencochrane** [comment]
When you login to a docker for aws node, you are actually logging into a container not the host. That is why you are not seeing the file. You can run a container and mount root in it, and then see the host file system if you want to see the file.
