### ISSUE TITLE
AMI cannot be described

### ISSUE THREAD

**Issue by vfarcic** [docker/for-aws#102]
### Expected behavior

A cluster created.

### Actual behavior

Cluster creation rolled back

### Information

  - Full output of the diagnostics from "docker-diagnose" ran from one of the instance

Getting `AMI cannot be described` as CF event and, from there on creation of the stack is rolled back.

  - A reproducible case if this is a bug, Dockerfiles FTW

I tried it a couple of time yesterday and today in both us-east-2 and us-west-1.

  - Page URL if this is a docs issue or the name of a man page

### Steps to reproduce the behavior

```bash
export AWS_ACCESS_KEY_ID=[...]
export AWS_SECRET_ACCESS_KEY=[...]
export AWS_DEFAULT_REGION=us-east-2

aws cloudformation create-stack \
    --template-url https://editions-us-east-1.s3.amazonaws.com/aws/stable/Docker.tmpl \
    --capabilities CAPABILITY_IAM \
    --stack-name devops22 \
    --parameters \
    ParameterKey=ManagerSize,ParameterValue=3 \
    ParameterKey=ClusterSize,ParameterValue=0 \
    ParameterKey=KeyName,ParameterValue=devops22 \
    ParameterKey=EnableSystemPrune,ParameterValue=yes \
    ParameterKey=EnableCloudWatchLogs,ParameterValue=no \
    ParameterKey=EnableCloudStorEfs,ParameterValue=yes \
    ParameterKey=ManagerInstanceType,ParameterValue=t2.small \
    ParameterKey=InstanceType,ParameterValue=t2.small
```

**Comment by kencochrane** [comment]
thanks, it looks like the AMIs are private for some reason, we will move them to public, and find out why they are private.

/cc @FrenchBen

**Comment by FrenchBen** [comment]
Thanks for reporting this issue - This should now be fixed @vfarcic
