### ISSUE TITLE
99% performance loss when using encrypted option in overlay network

### ISSUE THREAD

**Issue by rusanov** [docker/for-aws#103]
### Expected behavior
Use encryption in overlay network and achieve almost same performance as unencrypted

### Actual behavior
When setting encrypted=true option in overlay network bandwidth is around 1.4 Mbits/sec.
Even using option encrypted=false performance is the same.

### Information

  - Full output of the diagnostics from "docker-diagnose" ran from one of the instance
OK hostname=ip-172-31-18-183-ec2-internal session=1505996559-3SIFy1g6xU4CMV39walnCE5yOhs5O4pf
OK hostname=ip-172-31-32-99-ec2-internal session=1505996559-3SIFy1g6xU4CMV39walnCE5yOhs5O4pf
OK hostname=ip-172-31-7-30-ec2-internal session=1505996559-3SIFy1g6xU4CMV39walnCE5yOhs5O4pf
Done requesting diagnostics.
Your diagnostics session ID is 1505996559-3SIFy1g6xU4CMV39walnCE5yOhs5O4pf
Please provide this session ID to the maintainer debugging your issue.

  - A reproducible case if this is a bug, Dockerfiles FTW
  - Page URL if this is a docs issue or the name of a man page

### Steps to reproduce the behavior

  1. Create overlay network with option encrypted=true
`docker network create -d overlay --attachable -o encrypted=true iperf`
  2. On one node start iperf server
`docker run -ti --rm --net=iperf --name=iperf3-server -p 5201:5201 networkstatic/iperf3 -s`
  3. On different node start iperf client
`docker run -ti --rm --net=iperf  networkstatic/iperf3 -c iperf3-server`
  4. Delete overlay network
`docker network rm iperf`
  5. Create overlay network without any options
`docker network create -d overlay --attachable iperf`
  6. Repeat step 2 and 3
  7. Repeat step 4
  8. Create overlay network with option encrypted=false
`docker network create -d overlay --attachable -o encrypted=false iperf`
  9. Repeat step 2 and 3
  10. Compare results

**Comment by hairyhenderson** [comment]
I wonder if this is related? https://github.com/moby/moby/issues/33133

**Comment by FrenchBen** [comment]
Closing in favor of the above issue.
