### ISSUE TITLE
GovCloud testing

### ISSUE THREAD

**Issue by jjwilliams42** [docker/for-aws#108]
I originally posted this amended question here, but this forum appears to be dead:

https://forums.docker.com/t/docker-for-aws-in-gov-cloud/38909

I understand the documentation says that the China and GovCloud regions are not currently support, and that is fine with me.

All I need to know is: 

Is there some specific reason GovCloud support has been held back? Is it because some specific feature set in GovCloud is missing?

Before I spend several days / a week attempting to get it working, only to realize the stack depends on Feature X which GovCloud does not support.

I realize that GovCloud only has 2 AZ's. Looking through the template, I see no major reasons why it couldn't work. 

* There are conditionals for if Lambda is supported or not (which I think now GovCloud has Lambda)
* Conditionals for when only 2 AZ's are available
* The main thing I see missing are AMI mappings (after a cursory review)
* There is already a us-gov-west-1 entry in the AWSRegion2AZ map

**Comment by FrenchBen** [comment]
@jackjwilliams that's correct - AMI mapping is the only piece missing.
AWS mentioned that the AMI would need to be built in GovCloud and the customer would need to request the AMI for it to be made available to them, in order to keep things "secure"

What's your use case?

**Comment by jjwilliams42** [comment]
I have a client utilizing AWS GovCloud currently and want to update their infrastructure to something less rigid.

I guess I'm not understanding your statement in regards to the AMI being built in GovCloud, AWS GovCloud has a full set of Linux based AMIs. Below is a screenshot of my available AMI's when creating a new EC2 instance in GovCloud.

![image](https://user-images.githubusercontent.com/1746015/31155618-15d93958-a875-11e7-87bd-988139b3bc59.png)

**Comment by FrenchBen** [comment]
That's correct, the instance AMI are there, but you'll find that those AMI ID are GovCloud specific and can only be deployed to GovCloud regions. 
Our only offering in the GovCloud at the moment are linked to Docker EE.

**Comment by friism** [comment]
@jackjwilliams we have to get our custom AMIs into GovGloud - that's gonna require a little bit of elbow-grease on our part.

If you can't wait and if you want to experiment, you can always just install Docker on top of one of the existing AMIs that are already in GovCloud

**Comment by jjwilliams42** [comment]
I understand now, I assumed that the Docker for AWS scripts "just worked" with any Linux box. I didn't realize you guys had to hand craft them. 

Thank you for the information! I may just use your template as a starter to initiate a base swarm, then manually setup myself.

**Comment by gjackson12** [comment]
Did I read this correctly, that Docker EE for AWS, is available in GovCloud?

**Comment by jjwilliams42** [comment]
Negative, their docker boxes are hand crafted Ami's from my understanding, and are not available in Gov

**Comment by gjackson12** [comment]
So the only option is to start with one of the available AMIs and install Docker manually, and use something like Docker Swarm for orchestration? (since I believe ECS is not available)

**Comment by jjwilliams42** [comment]
Yep. I've actually taken their script, ripped out the specific ami parts and other unneeded parts to spin up managers / workers.

I'll still have to manually orchestrate the swarms initially, but the CloudFormation file only took a few hours to work out.

**Comment by gjackson12** [comment]
I'll have to take a look. Thank you for the help! 

This is making me re-consider leveraging Docker in GovCloud.
