### ISSUE TITLE
Syslog writes triplicate messages, causing disk to fill up faster

### ISSUE THREAD

**Issue by hairyhenderson** [docker/for-aws#111]
### Expected behavior

`/var/log/messages`, `/var/log/syslog`, and `/var/log/docker.log` should contain a minimum of redundant log messages.

### Actual behavior

`/var/log/messages`, `/var/log/syslog`, and `/var/log/docker.log` should contain a lot of redundant log messages.

Recently a few D4AWS-managed swarms I manage were plagued by some logging storms (the cause of which is a separate issue in `docker/libnetwork` and is logged at docker/libnetwork#1983), which caused these 3 log files to grow to ~5GBs _each_, all containing the same messages. One of the swarms had a quorum loss caused by lack of free disk space, and I had to recreate it from a snapshot. I was only able to keep the other swarms from the same fate by altering the `syslog` configuration (until I could fix the root cause the next day). 

The `/etc/syslog.conf` that ships in the Docker for AWS AMI (the `17.06.0-ce-aws2` version) sends `local0.*` messages to `/var/log/docker.log`. This is also covered by the `*.*;auth,authpriv.none` rule for `/var/log/syslog`, and because this particular message was at the `warning` level, the `*.=warning` rule for `/var/log/messages` also caught it.

For reference, here's the current config (minus comments):
```
auth,authpriv.*                 /var/log/auth.log
*.*;auth,authpriv.none              -/var/log/syslog
cron.*                          /var/log/cron.log
daemon.*                        -/var/log/daemon.log
kern.*                          -/var/log/kern.log
lpr.*                           -/var/log/lpr.log
mail.*                          -/var/log/mail.log
user.*                          -/var/log/user.log

local0.*                        -/var/log/docker.log

*.=debug;\
        auth,authpriv.none;\
        news.none;mail.none     -/var/log/debug
*.=info;*.=notice;*.=warning;\
       auth,authpriv.none;\
       cron,daemon.none;\
       mail,news.none          -/var/log/messages 
```

I patched the file as follows:

```patch
@@ -1,5 +1,5 @@
 auth,authpriv.*                 /var/log/auth.log
-*.*;auth,authpriv.none          -/var/log/syslog
+*.*;auth,authpriv.none,local0.none          -/var/log/syslog
 cron.*                          /var/log/cron.log
 daemon.*                        -/var/log/daemon.log
 kern.*                          -/var/log/kern.log
@@ -9,13 +9,3 @@
 local0.*                        -/var/log/docker.log
-
-*.=debug;\
-        auth,authpriv.none;\
-        news.none;mail.none     -/var/log/debug
-*.=info;*.=notice;*.=warning;\
-       auth,authpriv.none;\
-       cron,daemon.none;\
-       mail,news.none          -/var/log/messages 
```

With this altered configuration (and, after a `killall -HUP syslogd`) the rate of disk use slowed by 33%, and I was able to save a lot of space immediately by simply deleting the `/var/log/messages` file, since all its data was contained in `/var/log/syslog` anyway.

The amount of logs persisted to disk could be reduced even more if #69 were implemented.

**Comment by FrenchBen** [comment]
Thanks for sharing @hairyhenderson - Since you've looked into it more than I have, what do you lose by removing  the debug/info/notice/warnings?

**Comment by hairyhenderson** [comment]
@FrenchBen well overall I lose nothing, because those already all get routed to `/var/log/syslog`

**Comment by je-al** [comment]
Also, the problem is exacerbated by the fact that the default logging level for the engine seems to be debug (or is it just me?)

**Comment by hairyhenderson** [comment]
@je-al it's not just you - it is set to `debug`. Personally I'm OK with that - some of the info is useful when trying to troubleshoot a system. But the triplicate thing is _bad_ 😉

**Comment by je-al** [comment]
Or may it be that it's caused by https://github.com/docker/for-linux/issues/127 ?
'Cause I can see the `daemon.json` being generated in the template, and I'd assume the default is actually `info`?

**Comment by FrenchBen** [comment]
Sorry for the delay - I've made a patch against this, and also wrote a quick tool that updates our syslog:
https://hub.docker.com/r/docker4x/silence-syslog/

**Comment by hairyhenderson** [comment]
Thanks @FrenchBen! 🎉
