### ISSUE TITLE
Access docker daemon on AWS swarm manager via docker for windows

### ISSUE THREAD

**Issue by Mobe91** [docker/for-aws#115]
I have set up a docker swarm cluster on AWS as described [here](https://docs.docker.com/docker-for-aws/).
Now I would like to connect to the remote docker daemon from my local windows machine running docker for windows and I came up with the following approach:

- The docker daemon is bound to the `unix:///var/run/docker.sock` socket by default and to my knowledge, it is not possible to create a SSH tunnel to such a socket from Windows (correct me if I am wrong). Thus, I have to expose TCP access to the docker daemon by adding the following extension to the startup script contained in the EC2 manager instance user data.
```
    echo '"hosts": ["tcp://127.0.0.1:2375", "unix:///var/run/docker.sock"]' > /etc/docker/daemon.json
```
- However, the next issue is that SSH is exposed via a separate docker container (`shell-aws`) running on the manager instance. This container only has the docker unix socket available so my SSH tunnel to port 2375 on localhost won't work. I guess `--network=host` for starting the `shell-aws` container may work but I could not try it out because I could not figure out where the `shell-aws` container is actually launched. It does not happen in the user data startup script, maybe init-aws launches it?

Does anyone know how to accomplish this?

**Comment by friism** [comment]
You can set up a tunnel that terminates as TCP on Windows. This is what I do (in a cygwin shell):

    ssh -i ~/Downloads/friism-test.pem -NL localhost:2374:/var/run/docker.sock docker@34.209.212.148

Then I can use remote Docker by setting `DOCKER_HOST`:

    $env:DOCKER_HOST="tcp://localhost:2374"

**Comment by friism** [comment]
Also check out the docs: https://docs.docker.com/docker-for-aws/deploy/#manager-nodes

**Comment by Mobe91** [comment]
Great, I did not know that forwarding to a Unix socket was possible! Thank you!
