### ISSUE TITLE
Swarm manager attempts to deploy tasks to manager node for service with deploy mode global

### ISSUE THREAD

**Issue by Mobe91** [docker/for-aws#116]
Given a swarm cluster consisting of 1 manager node and 1 worker node.

### Expected behavior

For a service deployed with
```
deploy:
      mode: global
```
1 replica should be created on the worker node.

### Actual behavior

The swarm manager attempts to create 2 replicas, 1 on the worker node and 1 on the manager node. This is also indicated by the output of `docker service ls`:

```
ID                  NAME                MODE                REPLICAS            IMAGE                 PORTS
sc4d9chur83j        nginx_nginx         global              1/2                 nginx:1.13.6-alpine   *:80->80/tcp,*:443->443/tcp
```
Note that the deployment on the manager node fails because the swarm-scoped default network is not available there.

#### Diagnostics Output
```
OK hostname=ip-172-31-4-42-eu-central-1-compute-internal session=1510249234-6W05pL0hO4eIOiDwVH3FclpXBPgQSXYg
OK hostname=ip-172-31-0-232-eu-central-1-compute-internal session=1510249234-6W05pL0hO4eIOiDwVH3FclpXBPgQSXYg
Done requesting diagnostics.
Your diagnostics session ID is 1510249234-6W05pL0hO4eIOiDwVH3FclpXBPgQSXYg
Please provide this session ID to the maintainer debugging your issue.
```

**Comment by FrenchBen** [comment]
Please see the docs on replicated vs global services:
https://docs.docker.com/engine/swarm/services/#replicated-or-global-services

**Comment by Mobe91** [comment]
Just for the record, changing the stack file to
```yml
deploy:
  mode: global
  placement:
    constraints:
      - node.role == worker
```
yields the desired behavior.
