### ISSUE TITLE
Public IP address for swarm EC2 instances

### ISSUE THREAD

**Issue by Mobe91** [docker/for-aws#118]
### Expected behavior

The subnets created by the swarm cloud formation templates have `Auto-assign Public IP` set to `false`, hence I expect EC2 instances attached to these subnets to not have a public IP assigned.

### Actual behavior

EC2 instances in a swarm have a public IP assigned.

### Information
```
OK hostname=ip-172-31-4-42-eu-central-1-compute-internal session=1510742543-YUMXwtVKi7C77eZBKWp733owYDFNlHMk
OK hostname=ip-172-31-0-232-eu-central-1-compute-internal session=1510742543-YUMXwtVKi7C77eZBKWp733owYDFNlHMk
Done requesting diagnostics.
Your diagnostics session ID is 1510742543-YUMXwtVKi7C77eZBKWp733owYDFNlHMk
Please provide this session ID to the maintainer debugging your issue.
```

**Comment by Mobe91** [comment]
The reason probably is that `AssociatePublicIpAddress` is set to `true` for the worker launch configuration in the cloud formation template. Is there any reason for this?

**Comment by kencochrane** [comment]
If you do not have that set as true, then those hosts will not have internet access, and you would need to add a NAT gateway. If your workers don’t need any access to the public internet, then you can change to false. But most people need that, so it is defaulted to true.
