### ISSUE TITLE
Can't mount EBS volume: 'Permission denied' even though I am root

### ISSUE THREAD

**Issue by OmpahDev** [docker/for-aws#123]
I'm attempting to mount an EBS volume into a Docker for AWS instance and I'm getting permission denied errors even when attempting as root:

```
/ # mount /dev/xvdf /mnt/vol1
mount: permission denied (are you root?)
```

**Comment by ddebroy** [comment]
Can you try to start a container with the following privileges:  "CAP_SYS_ADMIN", "CAP_DAC_OVERRIDE", "CAP_DAC_READ_SEARCH" and try the mount from within that container.

**Comment by OmpahDev** [comment]
that worked, but it only happened inside that container.. how do I get it to mount directly on the box?

**Comment by ddebroy** [comment]
What exactly is your use case? Note that when you ssh into a Docker4AWS instance, you are inside a container called `shell` hosting the SSH server. The `shell` container does not have the necessary privileges required for mounting a device and even if it did, the volume would still be mounted only within the `shell` container. 

If you want contents a EBS volume presented as a docker volume to a EC2 host that other containers on the host can mount, you should use the `cloudstor` plugin that comes pre-installed with Docker4AWS: https://docs.docker.com/docker-for-aws/persistent-data-volumes/ . If it's a pre-existing EBS volume with data in it that you want to mount, you can add a couple of tags to the EBS volume to get it enumerated by `cloudstor` - if you need help with this let me know.

If you want to manually mount the EBS volume and `cloudstor` won't satisfy your needs, you need to drop into the root shell using `nsenter` and perform the mount in there. However this is not recommended.

**Comment by OmpahDev** [comment]
I simply need a DB container mounted.

Cloudstor is not installed on my cluster. I don't know if its because it's an older version of Docker for AWS that didn't have it or if I maybe forgot to set something in CloudFormation or what, but it's not there on my boxes. I searched around for ways to add Cloudstor to an already-existing cluster if it isn't there but that apparently requires blowing away the swarm and recreating it which I'm not willing to do.

Furthermore, to be completely honest I don't really trust cloudstor. My experience with Docker for AWS in general is that its stability leaves much to be desired, so I'd rather just use EBS directly.

I tried nsenter but that didn't work either.

**Comment by ddebroy** [comment]
What version of Docker/Docker4AWS are you running? If you run something along the lines of
```docker run -it --privileged --pid=host justincormack/nsenter1```
you should be able to access the root shell where all attached devices should show up allowing you to mount them.

Please note that the recommended way is to use `cloudstor` which you can install with the command below. `cloudstor` handles the provisioning, attachment and mount related actions for you as well as re-attach and mount the EBS volumes to any node where it is installed if the volume needs to be accessed from other nodes later.

```docker plugin install --alias cloudstor:aws --grant-all-permissions docker4x/cloudstor:17.06.2-ee-5-aws1 CLOUD_PLATFORM=AWS AWS_REGION=<aws-region>  AWS_STACK_ID=stack1  DEBUG=1 EFS_SUPPORTED=0```

where <aws-region> is the AWS region where the cluster exists. e.g: `us-west-1`, `us-east-2`

**Comment by shazChaudhry** [comment]
I have a use case where I need to mount '/var/lib/docker/containers/' directory to a docker swarm mode service. The service does not start because it can't locate '/var/lib/docker/containers/ path'

How do I mount '/var/lib/docker/containers/' directory from the host please in swarm mode when I am inside the shell/ssh container?

I have tried [--pid](https://docs.docker.com/engine/reference/run/#pid-settings-pid) option but I still get this error:

> "invalid mount config for type "bind": bind source path does not exist"

For those interested in a resolution for this issue, I am also tracking it at [Elastic Filebeat discussion](https://discuss.elastic.co/t/filebeat-on-docker-for-aws-fails-to-start/110345)

**Update** - My issue is resolved and is discussed at [Elastic Filebeat discussion](https://discuss.elastic.co/t/filebeat-on-docker-for-aws-fails-to-start/110345)

**Comment by FrenchBen** [comment]
Thanks for he following. Closing as reaolved
