### ISSUE TITLE
Adding SwarmWide security group to inbound rules of other security group outside swarm (same VPC) does not work

### ISSUE THREAD

**Issue by HosseinAgha** [docker/for-aws#125]
### Expected behavior
Adding SwarmWide security group id to inbound rules of an existing security group (for a instance outside swarm and inside same VPC) should make that security group (and corresponding) instances accessible to all swarm nodes.
   
### Actual behavior
I created a swarm inside same VPC of my ec2 instance.  
I added the SwarmWide security group id to inbound rules of that instance.    
I cannot access the instance from any of my swarm nodes (manager or worker)
Adding SwarmNode and SwarmManager security groups does not work either.

### Information
 It is normal for projects that are not completely containerized their stack to have existing legacy services outside the swarm stack. For example one of your DBs might not be containerized.   
Giving access to ec2 instance from swarm nodes using IP addresses is a real pain because nodes ip addresses change on every aws stack update. So we have to add new ip addresses again.   
It would be really appreciated if you make this possible.  
Thanks.

### Steps to reproduce the behavior

  1. Create a swarm using template for existing VPC
  2. Create a EC2 instance outside swarm but inside the same VPC
  3. Add SwarmWide security group to inbound rules of that instance's security group
  4. Try to make a request from one of the swarm nodes to that instance

**Comment by FrenchBen** [comment]
@HosseinAgha Thanks for opening the issue - At this time it's difficult for us to support all configuration out there, especially when using existing VPC. 
I would suggest going through the regular debugging steps to make sure that each machine can communicate with each other and that the new machine doesn't have any additional restrictions preventing communication.

**Comment by talolard** [comment]
Hi I can confirm this issue. 
In my case steps 1-3 are identical. I can make requests from master node but not from worker nodes. 
I'm not sure if this is a bug or just odd naming. The Swarmwide security group is only applied to my mater nodes, while the worker nodes have Docker-Node-VPC

Anyway, setting up the connection on both (to allow master=>outside and worker=>outside) did it for me

**Comment by HosseinAgha** [comment]
@FrenchBen, Could you put the CloudFormation template on github so community can contribute to it? As I understand your schedule is super busy and you don't have time to make minor fixes. I think this is the exact situation that community can help you.

**Comment by HosseinAgha** [comment]
@FrenchBen As I understand you have plans to migrate Docker for AWS to Infrakit so you can have more flexibility on issues like #24 and this.  
Could you please guide me to a doc or a repository for your migration roadmap to Infrakit?  
I was also curious to know that if you have any plans to put your work on Docker for AWS on github (or you already have?) so everybody can see its progress?

**Comment by FrenchBen** [comment]
@hosseinagha if you look at the infrakit repo, there is an example on booting up some machines within aws. 
The cfn example would need to be modified to create some of the networks needed.
