### ISSUE TITLE
Host mode ports not propogating to load balancer.

### ISSUE THREAD

**Issue by joel1st** [docker/for-aws#126]
### Expected behavior
When deploying a service with ports configured in `host` mode and deploy mode set to `global`, it should propogate those ports to the load balancer.

### Actual behavior
Only works as expected when the mode is `ingress` rather than `host`. When set to `host` the ports are not propogated to the load balancer. Manually updating the load balancer works, but gets overwritten on subsequent stack updates.

### Information
Previously we were setting `ingress` rather than `host` but this was problematic because of what appears to be a docker swarm external connectivity bug as outlined here: 
https://github.com/docker/for-aws/issues/121#issuecomment-348863178
For this reason we are now using `host` with `global`.

### Steps to reproduce the behavior

  1. Create a docker-compose version 3.3 with ports exposed in `host` mode with `deploy` mode set as global.
  2. Check load balancer for listener ports

**Comment by FrenchBen** [comment]
Closing in favor of https://github.com/docker/for-aws/issues/121#issuecomment-349119493
