### ISSUE TITLE
Can no longer ssh into a manager node

### ISSUE THREAD

**Issue by OmpahDev** [docker/for-aws#130]
One of my manager nodes no longer permits me to ssh into it.. . complains of `ssh: connect to host [ipaddress] port 22: Connection refused`" (note I've redacted the IP as [ipaddress])

Output of `ssh -vv`:

```
OpenSSH_7.5p1, OpenSSL 1.0.2k  26 Jan 2017
debug2: resolving "[ipaddress]" port 22
debug2: ssh_connect_direct: needpriv 0
debug1: Connecting to [ipaddress] [[ipaddress]] port 22.
debug1: connect to address [ipaddress] port 22: Connection refused
ssh: connect to host [ipaddress] port 22: Connection refused
```

The other manager nodes in the swarm are perfectly accessible. There are no problems with security group rules or firewalls or anything like that (I checked). My guess is whichever service handles ssh on that node probably died for some reason. How do I fix this situation and recover the node, without having to replace it?

**Comment by FrenchBen** [comment]
@sshorkey you do it via containers of course :P 
Plan of action would be:
1. Create a quick "heal" container
2. Deploy "heal" container from one of the manager with a target of the node ID that needs healing
3. SSH again into the healed node

The "heal" container would do things like:
* Bind mount the docker socket
* Bind mount the binary
* Have a script to restart/replace the shell container.

On the lazy side, you would deploy the same `docker4x/shell-aws` image to that Node, but with SSH running on a different port and the SG rules to allow that port to be reached.

**Comment by jarronshih** [comment]
I am having the similar issue here.

After I create a new Docker Cloud Swarm on AWS, I cannot access using ssh. I keep getting login error on the machine.
```
docker@<ip>: Permission denied (publickey,keyboard-interactive).
```
I try to `stop` and `start` the container but not work. I am not sure how to `heal` the container based on the step above.


Here's the shell-aws version I have in the machine.
```
docker4x/shell-aws                                                     17.12.0-ce-aws1
```

**Comment by FrenchBen** [comment]
@jarronshih `Permission denied (publickey,keyboard-interactive)` sounds like you're using the wrong key to SSH into the machine. I would verify that the key you selected during deployment is matching a key that you own. 

Closing in favor of https://github.com/docker/for-aws/issues/139
