### ISSUE TITLE
network flow collector

### ISSUE THREAD

**Issue by 4s4g4** [docker/for-aws#132]
### Expected behavior

// create a network and two services
> docker network create -d overlay test
> docker service create --name centos00 --network test centos ping 8.8.8.8
> docker service create --name centos01 --network test centos ping centos00

// do it in all nodes
> sudo apk add tcpdump
> sudo tcpdump -i any icmp

I expected to see some icmp traffic   :)

### Actual behavior

I can not see any traffic  :(

### Information

Is there a correct way to get the traffic between a container and an external point or between a container and another container (both in same or in different EC2 instances) ?

The idea is put an flow collector in some point to monitor all the network traffic.

Does anyone have an experience with this?

Thanks!

**Comment by FrenchBen** [comment]
The logs from the container that pings an existing container should show the ping results. 
Doing any kind of tcpdump on the local Host may not result anything if your service tasks are running on some other nodes. 
There plenty of container network docs out there. I would refer to that for more info.

**Comment by 4s4g4** [comment]
@FrenchBen Yes, you are right! Thanks!

> sudo tcpdump -i any icmp

" -i any " does not show anything but if I choose the correct interface I can see the icmp traffic. 

I read and tried a lot of things and, after all, I think the best way to see the entire swarm traffic is installing one network flow collector in each container. I know this will cause an excessive use of resources but I could not find another alternative.

Does anybody know if there is a " right way " to do that ? 

Thanks!
