### ISSUE TITLE
Swarm starts but log messages are not sent to syslog service and no logging errors are reported by docker daemon

### ISSUE THREAD

**Issue by chairbender** [docker/for-aws#133]
### Information

My docker stack consists of 

- a syslog container (a container which runs logstash, which accepts syslog messages for logging and sends them to an elasticsearch container)
- an elasticsearch container (for indexing the log messages, which uses cloudstor to store the index)
- several microservice containers. 

Inside my docker-compose, I've configured each microservice to depend on the syslog container and use the syslog logging driver to send logs to this container. The syslog service is published on port 5000 and accepts only TCP messages.

The trick with this setup (running the syslog service inside the same stack which talks to it) is that, when configuring the logging driver, I cannot use the syslog container's name as the hostname. I'd like to be able to put "syslog-address: tcp://syslog_container_name:5000", but I can't because this logging behavior happens outside of the docker network, at the level of the docker daemon.

One option I tried to get around this is to use the external hostname of my ELB: 
`syslog-address: tcp://external_ELB_host_name:5000 `
This works - logs from my microservices show up in my syslog container. To accomplish this, I had to allow external traffic to reach port 5000. Obviously I don't want to allow the public to access my syslog server, so I'd need to whitelist each of my manager and worker nodes. This doesn't seem to be a good option, because the whitelist would need to be updated every time D4AWS added worker nodes or the IP addresses changed. Perhaps there's some way to do this via AWS APIs or by messing with the cloudformation template but it seems like it could be a lot of work to figure out.

The other option I tried is to just use localhost: 
`syslog-address: tcp://localhost:5000`
I expected that this should work because of how docker swarm's routing mesh works - every node should be able to handle requests for any service, regardless of which node the actual service is running on. So, when the docker daemon on a given node looks at the log config and tries to send syslogs to tcp://localhost:5000, those messages should end up at my syslog container even if the microservice is not running on the same node as my syslog container. This definitely works when I run it locally using docker-compose.

But when I deploy to D4AWS, this behaves...very strangely and unexpectedly. 

As I understand it, if any container cannot send logs to the specified syslog service, it's supposed to fail to start. I verified that this happens when I point it at a nonexistant syslog service - when I run docker stack deploy, the containers fail to start and report an error about not being able to connect to the syslog service.

But what actually happens when I deploy to D4AWS is that all containers start and none of them complain about being unable to send messages to the syslog service. But no messages appear to be getting sent to the syslog service! I do not see them showing up in elasticsearch. And I know it's not a problem with the syslog container / config. I can simultaneously run the same stack on my local machine (using docker-compose) and point the log driver at the syslog service that's running in D4AWS and it works perfectly - logs from my local stack get sent to this syslog service on D4AWS and show up in elasticsearch on D4AWS. And I can manually send log events to this syslog container and see that they show up in elasticsearch.

So, why are the containers starting if they aren't able to send messages to my syslog service? And why aren't they able to send messages to my syslog service in the first place?

### Expected behavior

Microservice containers fail during docker stack deploy due to being unable to send messages to the syslog service. Or, messages get sent to the syslog service and show up in elasticsearch.

### Actual behavior

Microservice containers start up without error, but no messages seem to be sent to the syslog service and no messages show up in elasticsearch.

### Steps to reproduce the behavior

  1. Deploy a stack to D4AWS which contains ELK containers, with logstash accepting TCP syslog messages on port 5000 along with other containers in the same stack which write log messages to std out (such as a tomcat container). Configure the other containers to use the syslog driver and to point at tcp://localhost:5000. Or, instead of ELK, I think you can use any container which runs a syslog service as long as you have a way to see what logs have been received.
  2. Observe that the stack starts up without errors but logs do not seem to arrive at the syslog container.

**Comment by chairbender** [comment]
I'm going to try to craft a compose file so anyone can reproduce this - I can just use the syslog-ng image and a tomcat image I think.

**Comment by chairbender** [comment]
Looks like the problem is not with D4AWS. I can reproduce this locally.

Here's the compose file to use to reproduce it.

````
version: "3.3"

services:
  syslog:
    image: bobrik/syslog-ng
    ports:
      - "514:514"
  webservice:
    image: tomcat:8.5.13-jre8-alpine
    ports:
          - "8080:8080"
    depends_on:
      - syslog
    logging:
      driver: syslog
      options:
        syslog-address: tcp://localhost:514
        syslog-facility: daemon
        tag: "{{.Name}}/{{.ID}}"
````

When running this with docker-compose, log messages show up inside the syslog-ng container at /var/log/syslog-ng/... (keep going inside the folders to reach the log file).

When running this with docker stack deploy, the webservice starts without complaining but log messages do not show up in /var/log/syslog-ng. You can still cause logs to be generated by manually issuing a post request to localhost:514, but logs from the webservice container do not show up there no matter what.

I'm closing this as it appears to be a swarm issue rather than D4AWS.

**Comment by FrenchBen** [comment]
@chairbender thanks for the due diligence of reproducing this locally - Can you link to the moby/moby issue here once you've opened it, for future users?

**Comment by chairbender** [comment]
Oops, forgot to do that. Thanks for the reminder. Here is the moby issue: https://github.com/moby/moby/issues/35855
