### ISSUE TITLE
Stable Version has experimental true

### ISSUE THREAD

**Issue by EmilyShepherd** [docker/for-aws#136]
### Expected behaviour

The docs state that the edge channel comes with experimental features, implying that the stable channel does not. 

### Actual behaviour

Experimental mode is enabled when creating a stack from the stable cloud formation template.

### Information

Here's the output:

 ```
~ $ docker version
Client:
 Version:	17.12.0-ce
 API version:	1.35
 Go version:	go1.9.2
 Git commit:	c97c6d6
 Built:	Wed Dec 27 20:05:03 2017
 OS/Arch:	linux/amd64

Server:
 Engine:
  Version:	17.12.0-ce
  API version:	1.35 (minimum version 1.12)
  Go version:	go1.9.2
  Git commit:	c97c6d6
  Built:	Wed Dec 27 20:12:30 2017
  OS/Arch:	linux/amd64
  Experimental:	true
```

Here's the setting in the template:

```
~ $ wget -qO - https://editions-us-east-1.s3.amazonaws.com/aws/stable/Docker.tmpl | grep -A1 EXPERIMENTAL=
                                "export DOCKER_EXPERIMENTAL='true' \n",
                                "export NODE_TYPE='manager'\n",
--
                                "export DOCKER_EXPERIMENTAL='true' \n",
                                "export NODE_TYPE='worker'\n",
```

### Steps to reproduce the behavior

  1. Start a Stack

**Comment by FrenchBen** [comment]
Hi @EmilyShepherd thanks for the issue - The docker experimental features are usually enabled and bring the following:
https://github.com/docker/docker-ce/blob/master/components/cli/experimental/README.md

Although the wording is confusing, the experimental feature mentioned in the docs is in regards to Docker for AWS as a whole. For example, our distributed volume plugin, CloudStor, was first on the edge channel prior to being added to the stable channels. 

If you would like to turn off the docker experimental feature, you can do so in the CFN template, and why it's not hard-coded into the image.

**Comment by EmilyShepherd** [comment]
Ah, ok, thanks :smiley_cat:
