### ISSUE TITLE
Where do I find older versions of cloud formation template

### ISSUE THREAD

**Issue by DanielMaier-BSI** [docker/for-aws#14]
In the docs there is stated:
> You can only upgrade one version at a time. Skipping a version during an upgrade is not supported

But where can I find older Version of the template if I missed an upgrade?

BTW: What is your preferred channel for such questions, the forum or this issue tracker?

Thanks
Daniel

**Comment by kencochrane** [comment]
@DanielMaier-BSI it looks like they were removed from the release notes when we moved the docs, if you can tell me which one you are running, I can give you the links for the ones you are missing.

Either forum or this repo is fine for questions.

**Comment by DanielMaier-BSI** [comment]
We are not actually missing a version. It was more a question where we can find it in the future and also we would like to have a stable link to the current version. This means that in the future there are links in the release notes?

Thanks
Daniel

**Comment by hairyhenderson** [comment]
I'd also be interested in having old versions of the CFN templates kept - and the option of referencing a _versioned_ template URL would be very useful, that way we could be a little more explicit about which version we want to install/upgrade to.

**Comment by kencochrane** [comment]
What versions do you need, I'll compile the list, but I don't think we need every single one. If you let me know what you have now, I'll try and fill in the blanks.

**Comment by DanielMaier-BSI** [comment]
For us it is sufficient to have the current stable version as a "tagged" version and all future versions.

**Comment by joaofnfernandes** [comment]
@kencochrane if we're asking users to upgrade sequentially and don't skip versions I think we should make the old templates available in the docs as we release new ones. Can you ensure we include that in the AWS/Azure release notes when we ship new versions?

**Comment by cirocosta** [comment]
Are there any reasons for not keeping it versioned in this repo?

**Comment by kencochrane** [comment]
Here is a PR for adding a template archive page to the docs. https://github.com/docker/docker.github.io/pull/2605

**Comment by hairyhenderson** [comment]
Thanks @kencochrane! This should do nicely.

**Comment by hairyhenderson** [comment]
Looks like these are listed here now: https://docs.docker.com/docker-for-aws/archive/

Maybe this issue can be closed?

**Comment by kencochrane** [comment]
thanks, closing.
