### ISSUE TITLE
Add Support for the Kubernetes Scheduler

### ISSUE THREAD

**Issue by RehanSaeed** [docker/for-aws#140]
With Docker now supporting the Kubernetes as a scheduler, is Docker for AWS going to get support? If so, will the Kubernetes scaling project be in scope as I'd like to auto-scale nodes.

Also as an aside, I've seen that it's possible to use `docker stack deploy docker-stack.yml` to run on Kubernetes. Does this support all Kubernets options? Is this a migration path to Kubernetes or a long term supported option?

**Comment by FrenchBen** [comment]
Docker Enterprise Edition will be the support path. 
Please see the details of our Kubernetes integration here:
https://www.docker.com/kubernetes

The supported commands available on Docker for Mac, can be found here:
https://docs.docker.com/docker-for-mac/kubernetes/
