### ISSUE TITLE
Missing permission in documenation of IAM permissions

### ISSUE THREAD

**Issue by DanielMaier-BSI** [docker/for-aws#15]
### Expected behavior
When I do update the stack to another EC2 InstanceType the update should just work fine with the documented IAM permissions.
### Actual behavior
The update fails because of missing permission "autoscaling:DescribeScheduledActions"

### Steps to reproduce the behavior

  1. Use documented IAM permissions as AWS CloudFormation Service Role
  2. Start stack with default params
  3. Update stack with worker node "InstanceType" "t2.medium"

**Comment by kencochrane** [comment]
@DanielMaier-BSI are you describing these permissions? https://docs.docker.com/docker-for-aws/iam-permissions/ or the permissions that are in the IAM profile that we create inside of the stack?

**Comment by DanielMaier-BSI** [comment]
Yes I am describing these permission from the docs https://docs.docker.com/docker-for-aws/iam-permissions/. After adding the "autoscaling:DescribeScheduledActions" to them, all worked fine. So I think it is only a documentation issue, or are these permissions only meant to be used for create and delete but not for update?

**Comment by kencochrane** [comment]
Sorry for the delay, PR to include the change is here:  https://github.com/docker/docker.github.io/pull/2540

**Comment by kencochrane** [comment]
The other PR have been merged, so I'm going to close this, since it is now fixed. Thank you for reporting the issue.
