### ISSUE TITLE
 Where is located the raw logs from a container?

### ISSUE THREAD

**Issue by menosprezzi** [docker/for-aws#151]
I need to access the logs from a container to do some rotate management.
In others linux based OS, docker stores log output in `/var/lib/docker/containers/`, but this path doesnt exists in Moby. Why? And where is located that file if even docker says it located in with `docker inspect --format='{{.LogPath}}' $INSTANCE_ID` command?

**Comment by hairyhenderson** [comment]
In D4AWS, the daemon is configured to use the [awslogs](https://docs.docker.com/config/containers/logging/awslogs/) log driver by default. So they all get sent directly to CloudWatch Logs. You can of course configure a service to use a non-default logging driver, such as `json-file`, which will cause the logs to be written to disk under `/var/lib/docker/containers`.

**Comment by FrenchBen** [comment]
Thanks @hairyhenderson for chiming in. Closing as the question was answered

**Comment by ausarb** [comment]
Note that for someone to be able to see /var/lib/docker from within the ssh container, you'll need to do one of the following.

(Thanks to #169):
```
docker run -it --rm -v /:/host_root bash
chroot /host_root
```

OR

`docker run --privileged -it --rm -v /var/lib/docker:/var/lib/docker bash`
