### ISSUE TITLE
Upgrade to 18.03.1-ce

### ISSUE THREAD

**Issue by vce-xx** [docker/for-aws#158]
### Expected behavior

Want to be able to upgrade my docker swarm to 18.03.1-ce to address this bug: [No Service Events in Production Swarm #36834](https://github.com/moby/moby/issues/36834#event-1650744526)

### Actual behavior

Stable build is 18.03.0-ce

Is there a way to manually do this or do we need to wait for a new CF template?

**Comment by kinghuang** [comment]
@vce-xx If you manage the template yourself, you can just update the image IDs with the ones for 18.03.1-ce-aws1. I do this for my stacks.

For example, in us-west-2, the AMI ID are:
* `ami-ccf668b4` for 18.03.0-ce-aws1
* `ami-3260064a` for 18.03.0-ce-aws2 (fixes NVMe mount problem in c5/m5 instances)
* `ami-1aa8df62` for 18.03.1-ce-aws1

It'd still be nice if the actual template was updated by Docker. Seems a bit hit or miss.

**Comment by vce-xx** [comment]
Hello @kinghuang
Where did you find the info that ami-3260064a "Moby Linux 18.03.0-ce-aws2 stable" fixes NVMe mount problem in c5/m5 instances ?

**Comment by kinghuang** [comment]
@vce-xx I'm stating that based on #148 that I reported. `-aws2` was produced and it resolved the issue. Not sure if anything else changed in that release.

**Comment by skyzyx** [comment]
We're past this release now. This can probably be closed.

**Comment by joeabbey** [comment]
Should have closed this when 18.06.1-ce shipped.

Note: recently updated Docker for AWS to 18.09.2-ce.

https://download.docker.com/aws/stable/Docker.tmpl
https://download.docker.com/aws/stable/18.09.2-ce/Docker.tmpl

**Comment by vce-xx** [comment]
Fantastic !
Thank you @joeabbey
