### ISSUE TITLE
Wrong CIDR for NodeVpcSG and SwarmWideSG AWS SecurityGroups when using Existing VPC

### ISSUE THREAD

**Issue by ambrons** [docker/for-aws#18]
### Expected behavior
Cloudformation template to complete deploying successfully when using the [Deploy Docker Community Edition (CE) for AWS (edge) uses your existing VPC](https://console.aws.amazon.com/cloudformation/home#/stacks/new?stackName=Docker&templateURL=https://editions-us-east-1.s3.amazonaws.com/aws/edge/Docker-no-vpc.tmpl)

### Actual behavior
Cloudformation template hangs on `AWS::AutoScaling::AutoScalingGroup, NodeAsg Resource , creation Initiated`.  

### Information

Using the latest version of the Docker For AWS CE Edge Cloudformation Template for existing VPC (Docker for AWS 17.03.0-ce (edge)).
Followed the VPC / Subnet / Route recommendations from here: https://docs.docker.com/docker-for-aws/faqs/#recommended-vpc-and-subnet-setup

The `NodeVpcSG` and `SwarmWideSG` security groups are created with CIDR blocks `172.31.0.0/16`.  This causes the ELB to fail to put any of the instances `inService` and therefore they continually rebuild do to the instances / autoscaling group using ELB for healthcheck.

The work around is to change the `172.31.0.0/16` in the above two security groups to the existing VPCs CIDR and wait a minute and it'll continue as the manger and workers will be listed as `InService`.

### Steps to reproduce the behavior

1. Use the Docker for AWS 17.03.0-ce (edge) for existing VPC cloudformation template
2. Setup VPC / Subnets based on https://docs.docker.com/docker-for-aws/faqs/#recommended-vpc-and-subnet-setup, but make sure to use another address space for instance `172.20.0.0/16`.
3. Sit back and watch it fail.

**Comment by kencochrane** [comment]
Thank you for the report, I'll take a look.

**Comment by kencochrane** [comment]
@ambrons I'm trying to find a nice solution to this problem, but I'm currently limited by some constraints inside of CloudFormation. What I'm thinking about doing, is adding a new input parameter where you have to enter your VPC's CIDR. I tried to find a way where I could try and get that value directly from the VPC that you pick, but I wasn't able to find a way (if anyone knows of a way, please let me know.)

Would that work for you?

**Comment by ambrons** [comment]
@kencochrane That was my thought as well, so I'm good with that.

**Comment by hairyhenderson** [comment]
@kencochrane I'm a total CFN noob, but I _think_ you can do a `Fn::GetAtt` with `CidrBlock` as an argument - see the end of the "Return Values" section of http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ec2-vpc.html

But I may be misunderstanding the docs...

**Comment by kencochrane** [comment]
@hairyhenderson thanks for the tip, but I tried this already, and it doesn't work because in CloudFormation you can't get attributes for resources that are not created inside of your stack. With the bring your own VPC, we only have the VPC ID, and that is all. I wish you could get it's attributes, it would make my life so much easier.

**Comment by hairyhenderson** [comment]
Ah - I didn't realize, thanks @kencochrane... This kind of thing is why I abandoned CFN early on and use Terraform now almost exclusively 😉

**Comment by seriousben** [comment]
Workaround using jq:
```
url=https://editions-us-east-1.s3.amazonaws.com/aws/edge/Docker-no-vpc.tmpl

jq_script='
  (.Metadata."AWS::CloudFormation::Interface".ParameterGroups[] | select(.Label.default == "VPC/Network")).Parameters += ["VpcCidrBlock"] |
  .Resources.NodeVpcSG.Properties.SecurityGroupIngress[].CidrIp = {"Ref": "VpcCidrBlock"} |
  .Resources.SwarmWideSG.Properties.SecurityGroupIngress[].CidrIp = {"Ref": "VpcCidrBlock"} |
'

curl -sSL $url | jq "$jq_script" > Docker.tmpl
```

**Comment by kencochrane** [comment]
The next edge release will have a new parameter where you can pick your VPC CIDR block, when bringing your own VPC.

**Comment by kencochrane** [comment]
This is now available in latest edge release. https://download.docker.com/aws/edge/Docker-no-vpc.tmpl closing this issue.
