### ISSUE TITLE
Docker 18.09.0

### ISSUE THREAD

**Issue by anitgandhi** [docker/for-aws#183]
Hello, sorry if this is the wrong place to request this. Has work on Docker 18.09 CE for AmazonLinux already started? Some context: 

On our customized AmazonLinux1/ECS AMIs, we're facing a bug that more-or-less presents itself like this: https://github.com/golang/go/issues/24787 . After some digging, Docker won't come up when a certain agent on our instances is enabled; unfortunately disabling said agent is not an option for us. 

All Docker 18.06 packages on AL1/ECS AMI won't come up, but downgrading to 18.03 will work. Docker 18.03 was built with Go 1.9 which did not have this bug. The bug was introduced in Go 1.10, and a subsequent workaround/fix was introduced in Go 1.11 with the `osusergo` build tag (see https://github.com/moby/moby/pull/35739#issuecomment-379346230 for more info). 

I'm hoping that Docker 18.09 (release last week) will work for us because I believe it will be built with Go 1.11 with the new build tag. Right now, this is the list of available Docker packages on AmazonLinux1.

```
yum search --showduplicates docker
Loaded plugins: priorities, update-motd, upgrade-helper
=============================================================================================== N/S matched: docker ================================================================================================
docker-storage-setup-0.6.0-1.18.giteb688d4.amzn1.noarch : A simple service to setup docker storage devices
docker-17.12.1ce-1.135.amzn1.x86_64 : Automates deployment of containerized applications
docker-18.03.1ce-2.141.amzn1.x86_64 : Automates deployment of containerized applications
docker-18.03.1ce-5.0.amzn1.x86_64 : Automates deployment of containerized applications
docker-18.06.1ce-2.16.amzn1.x86_64 : Automates deployment of containerized applications
docker-18.06.1ce-3.17.amzn1.x86_64 : Automates deployment of containerized applications
docker-18.06.1ce-4.19.amzn1.x86_64 : Automates deployment of containerized applications
docker-18.06.1ce-5.22.amzn1.x86_64 : Automates deployment of containerized applications
```

If you need any more information, I'll be happy to provide what I can! If there's a better place I can request this, I can do that as well. I can also help with testing if needed!

Thank you!

**Comment by accnops** [comment]
Is there any progress?

Is it only available for AmazonLinux2? I'm also seeing 18.06 as latest available version, although 18.09 was released more than a month ago.

**Comment by hairyhenderson** [comment]
> Hello, sorry if this is the wrong place to request this.

@anitgandhi It is the wrong place to request this 😉

AmazonLinux is produced by AWS - you'll need to get in touch with them about their distributions.

This repo is about the product named _Docker for AWS_, which is a Docker Swarm deployment customized for AWS.

**Comment by anitgandhi** [comment]
Ahh sorry about that! I'll reach out to them on their forums. Thanks for the info, going to close this out.

**Comment by LennyPenny** [comment]
@anitgandhi did you get any response from them?

**Comment by anitgandhi** [comment]
@LennyPenny unfortunately I haven't posted on their forums about it; however, I did install Docker-CE 18.09 on a different AMI and it was built with Go 1.10, so I'm not sure the issue would have been resolved for us anyway.

**Comment by LennyPenny** [comment]
so you can manually install docker 18.09 on AMI?

**Comment by anitgandhi** [comment]
I installed it on a Ubuntu AMI, not AmazonLinux. I just wanted to see what version of Go was used in the Docker 18.09 package building process, and it was still Go 1.10, which doesn't help my original problem, unfortunately.
