### ISSUE TITLE
Upgrade to 18.09.2-ce

### ISSUE THREAD

**Issue by enbohm** [docker/for-aws#188]
### Expected behavior
Possibility to use (or upgrade to) Docker 18.09.x-CE.

### Actual behavior
Currently not possible, only 18.06.1-ce can be selected

### Information
Any timeplan when it will be possible to start using (or update to) Docker 18.09.2-CE via Cloudformation stack creation? Current version seems to be 18.06.1-ce but since 18.9.x is released (see https://github.com/docker/docker-ce/releases) it would be great to be able it use this version instead.

**Comment by jrupp** [comment]
In light of the secure patch that was added in 18.09.2, I would really hope that a new version release of For AWS would be happening ASAP.  +1

**Comment by joeabbey** [comment]
Updated Docker for AWS to 18.09.2-ce.

https://download.docker.com/aws/stable/Docker.tmpl
https://download.docker.com/aws/stable/18.09.2-ce/Docker.tmpl

Release notes:
https://docs.docker.com/docker-for-aws/release-notes/#18092
