### ISSUE TITLE
Docker EE AWS stuck at creating CloudFormation Stack, failing to receive resource signals.

### ISSUE THREAD

**Issue by adrrrrrrrian** [docker/for-aws#19]
### Expected behavior
I should be able to create the stack using the template offered by Docker EE.

### Actual behavior
It always stuck at creating auto scaling group for a very long time, and eventually will get this error message: **Failed to receive 3 resource signal(s) for the current batch,** and it will roll back.
### Information
Not applicable in this case.

### Steps to reproduce the behavior

1. Apply for Docker EE (AWS) 30 days trial;
2. Click the link which directs you to AWS CloudFormation page, and use this template(https://s3.amazonaws.com/awsmp-fulfillment-cf-templates-prod/7bfd682c-ff64-45a8-90b6-c0c4f405d3a1.93b19484-7f00-4c3b-9240-837da4d4a44a.template) to create a stack;
3. The only thing I touched in the setting is the SSH key, DDC password and Docker EE License Number.

**Comment by kencochrane** [comment]
@adrrrrrrrian we are sorry you were not able to get it working. From that error, it looks like the instances aren't able to finish booting for some reason. We just need to figure out what is causing your problem.

Can you include some more information to help us narrow down your issue?

1. Which region were you trying to use?
2. What instance type did you pick for managers and workers?
3. Does CloudFormation give you any other error besides the "Failed to receive 3 resource signal(s)?"
4. If you go into the EC2 dashboard while the managers are launching. Do you see the manager nodes starting? If so, if you look at the system system logs (click on checkbox next to instance name, and right click -> select instance settings -> Get System Log) do you see any errors? 

Another place to look for errors would be the EC2 Auto scaling group Activity History under the EC2 dashboard. 

If you can think of anything else, please let me know and I'll do my best to get you up and running.

**Comment by adrrrrrrrian** [comment]
@kencochrane 

Thank you for your response! 

Here are my answers: 
1. US-Ohio
2. I used default settings, I remember they are m3.medium and t2.micro.
3. No, only this error.
4. (1) There is no instance running in my EC2 dashboard. 
    (2) I didn't check system logs or AS group activity, I will run that again and give you updates tomorrow.

**Comment by adrrrrrrrian** [comment]
@kencochrane 

Found something in activity history of AS group, as I saw no instances in EC2 dashboard but there was an AS group created for Managers with activity history full of failures to create instances: 

**Description**: DescriptionLaunching a new EC2 instance. Status Reason: The requested configuration is currently not supported. Please check the documentation for supported configurations. Launching EC2 instance failed.

**Cause**: CauseAt 2017-03-22T13:43:23Z a user request update of AutoScalingGroup constraints to min: 0, max: 5, desired: 3 changing the desired capacity from 0 to 3. At 2017-03-22T13:43:27Z an instance was started in response to a difference between desired and actual capacity, increasing the capacity from 0 to 3.

**Comment by kencochrane** [comment]
@adrrrrrrrian OK, I think I know the issue. You are trying to use an instance size of m3.medium in US Ohio, which doesn't support that instance size. Try an m4.large instance size, and let me know if you are still having an issue.

We have talked with AWS to change out the default manager size, so this doesn't happen, but it looks like it hasn't been changed yet. Ping @uday-shetty

**Comment by uday-shetty** [comment]
Uploaded the new template last Thursday, it takes 3-5 days to show up. I'll ping them again.

Uday

**Comment by adrrrrrrrian** [comment]
@kencochrane @uday-shetty 

Thanks!

**Comment by kencochrane** [comment]
@adrrrrrrrian great to hear. Sorry for the trouble.

**Comment by kencochrane** [comment]
I'm going to close this issue.
