### ISSUE TITLE
Services are not running using cloudstor volume plugin

### ISSUE THREAD

**Issue by pindipoluravikumar** [docker/for-aws#20]
I am trying to run the Jenkins service using the below command

docker service create --name jenkins \
      -p 8082:8080 \
      -p 50000:50000 \
      -e JENKINS_OPTS="--prefix=/jenkins" \
      --mount "type=volume,volume-driver=docker4x/ cloudstor:aws-v17.03.1-ce-rc1-      03_22_2017,source=sharedvol1,destination=/shareddata" \
        jenkins:2.32.3-alpine

When i ran this command it's going to PENDING state forever

I used the stable version to create the cluster "https://editions-us-east-1.s3.amazonaws.com/aws/stable/Docker.tmpl". By default docker4x/cloudstor didn't installed so i installed the plugin using 
"swarm-exec docker plugin install --grant-all-permissions docker4x/cloudstor:aws-v17.03.1-ce-rc1-03_22_2017"

diagnostics session ID is 1490166250-ppJkPre7zhQQIs3krsYWG7CT4IBYSO9E

**Comment by kencochrane** [comment]
@pindipoluravikumar cloudstor is still beta, and currently isn't supported in the stable template. You are stuck in pending forever because the underlying EFS setup isn't done on the stable template, like it is in the edge template. If you want to try out cloudstor, I recommend using the edge template. Once we have enough people using cloudstor on the edge template, and they don't report any issues, we will move to the stable template.

ping @ddebroy incase I missed anything.

**Comment by ddebroy** [comment]
@kencochrane is absolutely correct. EFS is not provisioned by the stable template today since it's in beta at the moment. If you want to use cloudstor on your own outside the current edge template, you need to configure it to make it aware that it's in AWS as well as configure the EFS ID: `docker plugin install --alias cloudstor:aws --grant-all-permissions docker4x/cloudstor:aws-v17.03.1-ce-rc1- 03_22_2017 CLOUD_PLATFORM=AWS EFS_ID_REGULAR=$EFS_ID_REGULAR`

**Comment by kencochrane** [comment]
@pindipoluravikumar can we close this issue?

**Comment by cirocosta** [comment]
@ddebroy is this documented somewhere else? It looks very useful for those not trying out the edge version.

**Comment by ddebroy** [comment]
It's not documented since installing cloudstor out-of-band is not something we want to support at this point.

**Comment by kencochrane** [comment]
closing since cloudstor is only enabled in edge right now

**Comment by lvnilesh** [comment]
Used edge to create a swarm (1 manager 3 workers) in AWS using cloud.docker.com

```
ID                           HOSTNAME                                     STATUS  AVAILABILITY  MANAGER STATUS
a9xk878vtolozbv4asyhi0vyw *  ip-172-31-9-158.us-west-2.compute.internal   Ready   Active        Leader
owqxfybb5zjkdqi8e10j9axq4    ip-172-31-2-232.us-west-2.compute.internal   Ready   Active        
vek8jp8fwwc74egp3h2bcu4p7    ip-172-31-25-245.us-west-2.compute.internal  Ready   Active        
ybuba6d7qqakykhjy0owgc4ik    ip-172-31-41-79.us-west-2.compute.internal   Ready   Active   
```

export DOCKER_HOST=tcp://127.0.0.1:32770
openssl rand -base64 20 | docker secret create root_db_password -\n
openssl rand -base64 20 | docker secret create wp_db_password -\n
docker network create -d overlay wp\n
docker network create -d overlay traefik\n
docker network create -d overlay mariadb\n
docker stack deploy -c docker-compose.yml wp\n

docker plugin ls
docker service ps wp_wp
docker service inspect deh2gu2vuc7hw9o8lgg4ivfck
docker inspect k05kofo6i3v6
docker stack ps wp

docker plugin install --alias cloudstor:aws --grant-all-permissions docker4x/cloudstor:aws-v17.03.1-ce-rc1-03_22_2017 CLOUD_PLATFORM=AWS EFS_ID_REGULAR=$EFS_ID_REGULAR
aws-v17.03.1-ce-rc1-03_22_2017: Pulling from docker4x/cloudstor
3fcd1d11b821: Download complete 
Digest: sha256:e22a4a3c736b9cab20576027c1514ae04281acbb03919f0cb90fcb45031bed61
Status: Downloaded newer image for docker4x/cloudstor:aws-v17.03.1-ce-rc1-03_22_2017
Error response from daemon: dial unix /run/docker/plugins/ef7656da81abb579961bb885fc505a3f095db2b4a0932e1f5a80f5dd9a62ef62/cloudstor.sock: connect: no such file or directory

**Comment by ddebroy** [comment]
@lvnilesh If you spin up the cluster using cloud.docker.com, the EFS (and mount targets) are not created by the CFN template in 17.03. As a result, cloudstor will fail to initialize. If you want to use cloudstor in such an environment, you need to (1) create your own EFS and mount targets and (2) substitute `$EFS_ID_REGULAR` with the EFS ID in the command line you have above.

The EFS provisioning and cloudstor installation is only done in the Docker for AWS CE edge template released at https://docs.docker.com/docker-for-aws/#quickstart for 17.03.

**Comment by lvnilesh** [comment]
cloud.docker.com beta is broken.

**Comment by lvnilesh** [comment]
I succeeded with edge while using cloudformation directly

**Comment by barneyjackson** [comment]
I used the Docker for AWS CE edge template, but `docker plugin ls` on manager shows nothing. After manual installation using

    swarm-exec docker plugin install --grant-all-permissions docker4x/cloudstor:aws-v17.03.1-ce-rc1-03_22_2017

It then shows up, but enabled is false:
```
ID                  NAME                                                DESCRIPTION                       ENABLED
2bac0dcfe817        docker4x/cloudstor:aws-v17.03.1-ce-rc1-03_22_2017   cloud storage plugin for Docker   false
```

I tried `docker plugin upgrade <ID>` and then `docker plugin enable <ID>` but `enable` always seems to return

    Error response from daemon: dial unix /run/docker/plugins/<ID>/cloudstor.sock: connect: no such file or directory

Same result when run on worker node.

Am I missing something or is CloudStor not working on Edge?

**Comment by ddebroy** [comment]
@barneyjackson with 17.03, you need to try a region where EFS support is present like Ohio,
 N. Virginia and Oregon (https://aws.amazon.com/about-aws/global-infrastructure/regional-product-services/). Also make sure you chose `yes` for `Create EFS prerequsities for CloudStor?`

**Comment by barneyjackson** [comment]
Starting the stack in one of the above regions caused the plugin to install correctly.

It would be great if this was mentioned in the docs.

**Comment by ddebroy** [comment]
Thanks for the feedback. I will clarify the regions for EFS in the docs.

**Comment by RehanSaeed** [comment]
I've done a fresh stable install in the Ireland region which supports EBS/EFS and my plugin is installed but disabled from the get go. I've raised https://github.com/docker/for-aws/issues/85

> Error response from daemon: dial unix /run/docker/plugins/038e08d3f72ba67503691db2521ba669711f930df5d4a3afd9664b915038f2de/cloudstor.sock: connect: no such file or directory
