### ISSUE TITLE
meta-aws crashing if no PublicIPs are associated with the cluster

### ISSUE THREAD

**Issue by netflash** [docker/for-aws#29]
### Expected behavior

All the master nodes should join the cluster

```
~ $ docker logs meta-aws
AWS service
Path:[GET] /token/manager/
User: Wget [10.10.A.B:56460]
userIP: 10.10.A.B on port 56460

Path:[GET] /token/manager/
User: Wget [10.10.C.D:60960]
userIP: 10.10.C.D on port 60960

Path:[GET] /token/worker/
User: Wget [10.10.E.F:56708]
userIP: 10.10.E.F on port 56708
```

### Actual behavior

Only master/leader node is in, other master nodes can't join.
Not sure if that is related to PublicIPs or some other issue :-(

```
docker logs meta-aws

GPath:[GET] /token/manager/
User: Wget [10.10.N.M:44646]
userIP: 10.10.N.M on port 44646

2017/04/07 21:24:18 http: panic serving 10.10.N.M:44646: runtime error: invalid memory address or nil pointer dereference
goroutine 478 [running]:
net/http.(*conn).serve.func1(0xc420382d00)
	/usr/local/go/src/net/http/server.go:1491 +0x12a
panic(0x7927a0, 0xc420014040)
	/usr/local/go/src/runtime/panic.go:458 +0x243
main.awsInstances(0xc4204e18b0, 0x2, 0x2, 0x1, 0x2, 0xc4204e18b0)
	/go/src/metaserver/aws.go:159 +0x55e
main.AWSWeb.Managers(0xf6a07000, 0xc420467780, 0x418513)
	/go/src/metaserver/aws.go:90 +0x31b
main.(*AWSWeb).Managers(0x9f75d8, 0x41484f, 0x7c33e0, 0x9f75d8)
	<autogenerated>:3 +0x4d
main.isManagerNode(0x9beb40, 0x9f75d8, 0xc42025cd00, 0xb, 0x9f75d8)
	/go/src/metaserver/utils.go:160 +0x31
main.AWSWeb.TokenManager(0x9bd620, 0xc4200ec270, 0xc4203ad770)
	/go/src/metaserver/aws.go:24 +0xe0
main.(*AWSWeb).TokenManager(0x9f75d8, 0x9bd620, 0xc4200ec270, 0xc4203ad770)
	<autogenerated>:1 +0x6a
main.(Web).TokenManager-fm(0x9bd620, 0xc4200ec270, 0xc4203ad770)
	/go/src/metaserver/main.go:82 +0x4d
net/http.HandlerFunc.ServeHTTP(0xc42021dca0, 0x9bd620, 0xc4200ec270, 0xc4203ad770)
	/usr/local/go/src/net/http/server.go:1726 +0x44
metaserver/vendor/github.com/gorilla/mux.(*Router).ServeHTTP(0xc42020ecd0, 0x9bd620, 0xc4200ec270, 0xc4203ad770)
	/go/src/metaserver/vendor/github.com/gorilla/mux/mux.go:114 +0x10d
net/http.serverHandler.ServeHTTP(0xc42021ae80, 0x9bd620, 0xc4200ec270, 0xc4203ad0e0)
	/usr/local/go/src/net/http/server.go:2202 +0x7d
net/http.(*conn).serve(0xc420382d00, 0x9bdce0, 0xc4206028c0)
	/usr/local/go/src/net/http/server.go:1579 +0x4b7
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:2293 +0x44d
```
and the container `docker4x/init-aws` shows this

```
Get Primary Manager IP
MANAGER_IP=10.10.X.Y
PRIMARY_MANAGER_IP=10.10.X.Y
wget: error getting response
```

### Information

Latest CF template from #18 
`meta-aws` version is docker4x/meta-aws:17.04.0-ce-aws1
and `init-aws` version is `docker4x/init-aws:17.04.0-ce-aws1`

### Steps to reproduce the behavior

custom template from #28

**Comment by kencochrane** [comment]
Do you have a gateway or a nat setup so that the nodes can connect to the internet? The meta container needs to be able to connect to the AWS API, and I'm wondering if that is getting blocked. Which is causing the crash.

**Comment by netflash** [comment]
NAT gateway exists in those private subnets, also these nodes can reach 169.254.169.254.
More to say, I've checked twice - same VPC and subnets, one deployment with PublicIPs enabled works fine. Then I've deleted this stack and deployed another one with PublicIPs disabled and here we go ^^^

**Comment by kencochrane** [comment]
The 169.254 IP address is for the ec2 metadata service, this is different from the AWS API, which I believe requires access to the public internet. When you remove the public IPs you lose access to the public internet.

**Comment by netflash** [comment]
Well... I have a NAT gateway In the private subnets, which provides access to the internet for those instances. So it shouldn't be a problem. And anyway I don't think that the app should just crash, at least it should some some more human-friendly error.

**Comment by kencochrane** [comment]
I agree, it shouldn't crash, and we will fix that. I'm just trying to figure out what makes it crash with your setup so that we can fix it.

**Comment by netflash** [comment]
Anything I can help with ? some more debug information ?

**Comment by kencochrane** [comment]
@netflash one thing, could you let me know how you have your private subnets setup, nat, internet gateway, etc. This way I can look to reproduce locally. thanks

**Comment by netflash** [comment]
Would it be helpful if I point you to a terraform module I used to build the whole VPC ?

In the meantime - quick overview - 

1 VPC in 3 AZs,
each AZ has one private subnet and one public subnet, so total 6 subnets.

Public subnets have 1 Internet gateway, and one VPN server inside of one of the subnets.
Route tables - 1 per all the public subnet -  with 0.0.0.0/0 point to Internet Gateway.

Private subnets have one NAT gateway per subnet.
Route tables - 1 per subnet - with 0.0.0.0/0 points to a NAT gateway tightened to that subnet.
And I confirmed, that instances have access to the internet.

VPC has it's own private route53 zone and DHCP options set to use that DNS server and domain-name.

Network ACL - default.

**Comment by kencochrane** [comment]
Just to give an update, I found the cause of the meta server crash, it assumed there was a public IP, and when it was missing, it didn't fail in a nice way. PR has been submitted, once approved, it will be available in 17.05

**Comment by netflash** [comment]
@kencochrane nice!

Any way to track the releases ? Not sure where do you guys keep the CHANGELOG or releases. This repo doesn't look like that place for that.

Thank you!

**Comment by kencochrane** [comment]
@netflash the release notes are here: https://docs.docker.com/docker-for-aws/release-notes/ but there currently isn't a way to track the release before it gets out the door.

**Comment by netflash** [comment]
Thanks again!

**Comment by netflash** [comment]
FYI I confirm that it is fixed and works as desired. I can have a cluster in private subnet without public IPs

**Comment by kencochrane** [comment]
@netflash thanks for the update, glad you got it working.
