### ISSUE TITLE
Can't mount EFS: permission denied (are you root?)

### ISSUE THREAD

**Issue by charly-vega** [docker/for-aws#3]
### Expected behavior
Running Docker for AWS version 1.13.0-1, with 3 manager nodes, with the stock `ami-3f9a7329` image. Trying to mount an EFS manually as per the *Amazon EC2 mount instructions* to a custom `/mnt/efs` path, but I'm getting a `permission denied` error.

### Actual behavior
Running:
```
sudo mount -t nfs4 -o nfsvers=4.1,rsize=1048576,wsize=1048576,hard,timeo=600,retrans=2 fs-XXXXXXXX.efs.us-east-1.amazonaws.com:/ /mnt/efs
```
fails with:
```
mount.nfs4: Operation not permitted
mount: permission denied (are you root?)
```
### Steps to reproduce the behavior

- Create a file system at the EFS console https://console.aws.amazon.com/efs
- Place it on the same VPC as the CloudFormation-initialized swarm, and attach it to the `SwarmWideSG` security group so it's accessible from every host in it
- Connect to a manager in the swarm, and run the following:
```
sudo apk update
sudo apk add nfs-utils
sudo mkdir /mnt/efs
sudo mount -t nfs4 -o nfsvers=4.1,rsize=1048576,wsize=1048576,hard,timeo=600,retrans=2 fs-XXXXXXXX.efs.us-east-1.amazonaws.com:/ /mnt/efs
```
(also tried switching users to `root` to no avail)

Thanks in advance!

**Comment by kencochrane** [comment]
The AMI is locked down for security reasons, and that is probably why it is failing. We are working on a way to make this doable in future releases. 

/cc @ddebroy

**Comment by nathanleclaire** [comment]
SSH container is in its own mount namespace for starters and probably needs at least additional capabilities to make this work, you might want to see if you can get a mount working in a `--privileged` container

**Comment by nathanleclaire** [comment]
But as @kencochrane, we're working on first class support for this

**Comment by charly-vega** [comment]
Awesome, thanks!

Sticking with Ubuntu-based AMIs for now as we need to have some sort of storage engine in place (REXRay), but I will sure keep trying out Docker for AWS as it evolves.

**Comment by ddebroy** [comment]
@charly-vega When you ssh in to a Docker for AWS node, please note that you end up in a special `shell` container which does not run in privileged mode. For you to be able to mount a NFS share, you need to start another container (where you will run your workload) with the necessary capabilities to mount a file system. Please try the following:

`docker run -ti --cap-add SYS_ADMIN --cap-add DAC_OVERRIDE --cap-add DAC_READ_SEARCH alpine /bin/sh`

 ```/ # mkdir /mnt/efs1
/ # mount -t nfs4 -o nfsvers=4.1,rsize=1048576,wsize=1048576,hard,timeo=600,retrans=2 fs-8bbe7022.efs.us-west-2.amazonaws.com:/ /mnt/efs1/```

**Comment by kencochrane** [comment]
In [beta 18](https://docs.docker.com/docker-for-aws/release-notes/#/beta18) we have added support for EFS volumes and Cloudstor, please take a look and see if this works for you.

**Comment by charly-vega** [comment]
@kencochrane This sounds great. We were on our way to setup a higher-level storage solution with REX-Ray, but Cloudstor seems to offer the same functionality we're after. Will take if for a spin shortly.

The introduction of Cloudstor plus being able to mount an EFS with @ddebroy 's process I think cover my original concerns in this issue.

Thanks for your quick responses!

**Comment by kencochrane** [comment]
Ok, going to close this issue, then.

**Comment by alexsandro-xpt** [comment]
So, what is the solution for that?

I would like add an NFS( AWS EFS ) for my Swarm cluster. My desire is mont it at `/var/lib/docker/volumes/`

**Comment by ddebroy** [comment]
@alexsandro-xpt You can use EFS through the `cloudstor` Docker volume plugin that comes pre-packaged (currently in edge only but will soon be in stable with 17.06). You can find the details here: https://docs.docker.com/docker-for-aws/persistent-data-volumes/

**Comment by alexsandro-xpt** [comment]
Alright @ddebroy, but How can I preserve the EFS Services deletation? I'm asking it because I could want migrate the EFS to another Swarm cluster. Any ideia? Thanks
