### ISSUE TITLE
r4 instances are not available for eu-west-2

### ISSUE THREAD

**Issue by davidwindell** [docker/for-aws#43]
We are using Docker Cloud and expect to find r4 instance types when choosing `eu-west-2 (London)` however these aren't available.

**Comment by kencochrane** [comment]
Those should be available in 17.04, but it depends on what version docker-cloud is using. 

/cc @amegianeg

**Comment by amegianeg** [comment]
@kencochrane @davidwindell 
- Stable channel: 17.03.1-ce
- Edge channel: 17.04.0-ce

**Comment by kencochrane** [comment]
@amegianeg thank you. @davidwindell which channel are you using? I'm assuming you are using the stable one if r4 isn't available to you.

**Comment by amegianeg** [comment]
@kencochrane we are about to release 17.05.-ce edge channel

**Comment by davidwindell** [comment]
@amegianeg thanks! How do we switch to Edge? It looks like our nodes are deployed with 1.11.2 at the moment.

**Comment by amegianeg** [comment]
@davidwindell but that version is not Swarm mode, right? are you using Docker Cloud "classic" mode? nodes and node clusters

**Comment by davidwindell** [comment]
@amegianeg We're using "classic" mode.

**Comment by mghazizadeh** [comment]
@davidwindell Docker for AWS is supported on Docker Cloud only through Swarm Mode. Docker Cloud Swarm Mode is in public beta and does not (yet) have a UI for managing Swarm Clusters. Docker Cloud Swarm mode (on AWS) currently supports Docker CE Stable (17.03.1-ce) and Edge (17.04.0-ce). Hope that helps.

**Comment by davidwindell** [comment]
@mghazizadeh thanks, Docker Cloud email support told me to reach out here so I'll go back to them and see if r4 can be added to "Classic".

**Comment by amegianeg** [comment]
@davidwindell will take a look at it soon

**Comment by amegianeg** [comment]
@davidwindell r4 family is in production

**Comment by davidwindell** [comment]
Awesome thanks!
