### ISSUE TITLE
REQ allow option to enable experimental features of docker

### ISSUE THREAD

**Issue by andrewhsu** [docker/for-aws#44]
Would like a way to enable [experimental flag](https://github.com/moby/moby/tree/master/experimental#use-docker-experimental) on all docker nodes when launching an AWS CloudFormation stack.

**Comment by kencochrane** [comment]
Experimental flag is on by default for all edge releases, and disabled for stable releases. Which version are you looking for it to be enabled for?

**Comment by kencochrane** [comment]
@andrewhsu Are you requesting for support on stable?

**Comment by andrewhsu** [comment]
just support for experimental features on edge releases would be good

**Comment by kencochrane** [comment]
@andrewhsu we do that today, experimental is enabled by default on all edge releases.

**Comment by andrewhsu** [comment]
synced up with @friism about this and i'll have the linux distro packages default settings also have experimental enabled in the 17.06.0 docker-ce edge release

**Comment by kencochrane** [comment]
@andrewhsu cool, is this issue good to close then?
