### ISSUE TITLE
Kill one machine and replace it by a new instance?

### ISSUE THREAD

**Issue by goloroden** [docker/for-aws#49]
This question is derived from #47 … when running Docker for AWS, is it possible to kill one EC2 worker instance and make Swarm automatically replace it by a new instance?

Or, in other words: How can I replace a malfunctioning instance by a new one, without much manual hassle?

**Comment by friism** [comment]
Killing an instance in the AWS console should cause the machine to be replaced. The workers are in an autoscaling and will be replaced: http://docs.aws.amazon.com/cli/latest/reference/autoscaling/terminate-instance-in-auto-scaling-group.html#examples

**Comment by kencochrane** [comment]
@goloroden do you have any other questions? can we close this issue now?

**Comment by goloroden** [comment]
Sorry for not having closed this already.

Yes, my original question has been answered 😊 
Thanks for your help, @friism!
