### ISSUE TITLE
CloudFormation Upgrade Error

### ISSUE THREAD

**Issue by netflash** [docker/for-aws#50]
### Expected behavior
Upgrade from 17.04-ce to 17.05-ce goes smoothly without errors

### Actual behavior
Facing an error from CloudFormation
```
14:59:17 UTC-0700	UPDATE_FAILED	AWS::AutoScaling::AutoScalingGroup	ManagerAsg	MinInstancesInService must be less than the autoscaling group's MaxSize
```
### Information
I have a cluster with 5 manager instances. Can't upgrade it with default template because of the issue mentioned above.

Template has to be updated at line 1101, below parameter should be bigger than 5.
```
                "MaxSize": 5,
```

**Comment by kencochrane** [comment]
@netflash thank you for reporting the issue, we will be sure to include the fix in 17.06 release.

Just curious did you make the change yourself, and with that change did it work as expected? What value did you change it too, 6?

**Comment by netflash** [comment]
@kencochrane yeah, I did. 6 is good enough. It works.
are there any chances you will put that CF template into a git repository so people can fork it ?

**Comment by kencochrane** [comment]
@netflash thank you, the fix will be in 17.06

**Comment by netflash** [comment]
I assume we can close it, right ?

**Comment by FrenchBen** [comment]
closing as it's been addressed and labelled as such.
