### ISSUE TITLE
Fetching token from metaserver results in timeout

### ISSUE THREAD

**Issue by natefaerber** [docker/for-aws#51]
### Expected behavior

init-aws requests a token from the metaserver when turning up a cluster.  metaserver should not timeout returning the token.

### Actual behavior

I can connect to the service on port 9024 but the wget call results in a timeout and the cluster cannot be created.

### Information

  - aws-v17.03.1-ce-aws2
  - This is a customized version of the CF template that puts the nodes in private subnets.
  - The private subnets have a nat route and the fact that the docker containers are downloaded during startup proves it has internet access.
  - Source code for metaserver is not available so I have no chance to troubleshoot this.  Will metaserver and loadbalancer ever be made available to the community?

### Steps to reproduce the behavior

  1. Customize user_data to send system container logs to aws
  2. Turn up cluster with customized CF that puts nodes on private subnets.
  3. Watch cloudwatch logs to see timeout when requesting TOKEN.
  4. See no logs from meta-aws other than "AWS service"

**Comment by kencochrane** [comment]
Sounds related to https://github.com/docker/for-aws/issues/29 which was fixed in 17.05, and will be available in 17.06 stable.

**Comment by natefaerber** [comment]
The reason I didn't think it was #29 was because I wasn't getting a log message.  Is there a debug flag I'm missing?

Also, will there be documentation for metaserver and loadbalancer?  Better yet, will source be available?

**Comment by netflash** [comment]
Exactly. I had errors in logs. And if you are getting timeouts - that could be a network

**Comment by natefaerber** [comment]
This issue appears to be that a stale Manager IP existed in the DynamoDB table.  Both workers and managers took this to be the leader and tried talking to it.

**Comment by kencochrane** [comment]
@natefaerber thanks for the update. The leader should have noticed this, and updated the record, did it not happen?
