### ISSUE TITLE
Cloudstor plugin not installed, manual install has socket error

### ISSUE THREAD

**Issue by barneyjackson** [docker/for-aws#53]
### Expected behavior

Cloudstor aws plugin installed

### Actual behavior

No plugins installed. Manual install results in error:

    Error response from daemon: dial unix /run/docker/plugins/<ID>/cloudstor.sock: connect: no such file or directory

### Information

`docker-diagnose` session ID: `1498248299-gNOAvt74u81SjYaHRIGfQSnMMV6rusut`

### Steps to reproduce the behavior

I used the Docker for AWS CE edge template (https://console.aws.amazon.com/cloudformation/home#/stacks/new?stackName=Docker&templateURL=https://editions-us-east-1.s3.amazonaws.com/aws/edge/Docker.tmpl)

"Enable CloudStor" was definitely set to "yes" in the AWS design tool.

After launch, `docker plugin ls` on the manager shows no plugins. 

After manual installation using

    swarm-exec docker plugin install --grant-all-permissions docker4x/cloudstor:aws-v17.03.1-ce-rc1-03_22_2017

It then shows up, but enabled is false:

```
ID                  NAME                                                DESCRIPTION                       ENABLED
2bac0dcfe817        docker4x/cloudstor:aws-v17.03.1-ce-rc1-03_22_2017   cloud storage plugin for Docker   false
```

I tried `docker plugin upgrade <ID>` and then `docker plugin enable <ID>` but `enable` always seems to return

    Error response from daemon: dial unix /run/docker/plugins/<ID>/cloudstor.sock: connect: no such file or directory

Same result when run on worker node.

Am I missing something or is CloudStor not working on Edge?

Update:
I tried installing using the most recent tag I could find in the docker4x/cloudstor repo (17.06.0-ce-rc5-06_23_2017-aws1) and got the same results

**Comment by barneyjackson** [comment]
As per @ddebroy's comment [here](https://github.com/docker/for-aws/issues/20#issuecomment-310759476), starting the stack in one of the Ohio, N. Virginia and Oregon regions caused the plugin to install correctly.

It would be great if this was mentioned in the docs.

**Comment by kevin-cantwell** [comment]
I know this is closed, but I'm running into an almost identical error. For me, the plugin is installed (I'm using N. Virginia), but support for EFS is not enabled. I can alter the settings and add the EFS ID, but any attempt to re-enable the plugin results in the same missing sock file error you get. I've created a [topic in the forum](https://forums.docker.com/t/enable-efs-for-cloudstor-aws-plugin/37447/2) but if anyone else in this internet wasteland sees this message and can offer help, please do!
