### ISSUE TITLE
Cloudformation Template for existing VPC in stable channel 

### ISSUE THREAD

**Issue by netflash** [docker/for-aws#59]
Is there any plans to have cloudformation template for existing VPC in stable channel ?
Right now there is a template "With a new VPC created by Docker" :-(

**Comment by kencochrane** [comment]
@netflash yes, we have one for 17.06, we need to update the docs so they include the option now. Thanks for reminding us. Here is the URL: https://editions-us-east-1.s3.amazonaws.com/aws/stable/Docker-no-vpc.tmpl

**Comment by kencochrane** [comment]
Here is a link to the PR for updating the docs: https://github.com/docker/docker.github.io/pull/3823
