### ISSUE TITLE
Add Labels for Nodes based on placed Availability Zone

### ISSUE THREAD

**Issue by kacole2** [docker/for-aws#6]
### Expected behavior
We have successfully been able to use EBS with Docker for AWS.

By default, Docker for AWS will deploy both manager and worker nodes in the same region but across multiple availability zones. This increases the high availability because a failed node will trigger the restart of the container to a new host which may be in a different availability zone. However, a limitation of EBS is that a volume is only accessible to hosts in the same availability zone. 

Alternatively, a better way to go about making sure containers have access to their EBS volumes would be through the use of [node label metadata](https://docs.docker.com/engine/swarm/manage-nodes/#/add-or-remove-label-metadata). A feature request is to have each node be assigned a label automatically based on it’s placed availability zone. At this point, hosts can be spread across zones and containers can be constrained based on the node label. If 3 of my 8 deployed nodes have been given the label `az=us-east-1b`, then I can create a service that constrains the container to only run on hosts in that zone:

```
$ docker service create --replicas 1 \
  --mount type=volume,target=/data,source=data,volume-driver=rexray/ebs \
  --constraint 'node.labels.az == us-east-1b' busybox
```

### Actual behavior
Nodes are not given any labels.

**Comment by nathanleclaire** [comment]
Yeah, we've definitely thought about doing this automatically. Anything you'd be interested in besides region / AZ?

**Comment by kacole2** [comment]
off the top of my head
 

- availability zone
- instance type

I don't really think things like keyname , public dns, or other things in the dashboard really should have that much impact.

**Comment by hairyhenderson** [comment]
@nathanleclaire It'd be really useful to have EC2 tags available as labels too 🙂

**Comment by kencochrane** [comment]
In [beta 18](https://docs.docker.com/docker-for-aws/release-notes/#/beta18) we have added the following tags to docker:
- **os** (linux)
- **region** (us-east-1, etc)
- **availability_zone** (us-east-1a, etc)
- **instance_type** (t2.micro, etc)
- **node_type** (worker, manager)

**Comment by kencochrane** [comment]
@hairyhenderson can you give an example for what you are looking for in regards to adding EC2 tags? Where do you set the EC2 tags (in cloudformation, etc)? I want to make sure I understand what you are asking.

**Comment by hairyhenderson** [comment]
@kencochrane yeah, in CFN. In my understanding the tags are actually applied to all resources created by CFN (not just EC2 - so I was mistaken). As far as use-case, we often tag with "Environment" (e.g. to differentiate between "dev" or "prod"), or "Owner" so we know who to blame when a set of instances get expensive 😉.

I'm not _necessarily_ sure that we'd make scheduling decisions based on _those_ kinds of tags, but it'd be useful to have that kind of metadata available anyway. One reason is that sometimes it's desirable to deny the ability of containers to talk to the EC2 metadata API for security reasons, but it'd be nice for those containers to still be able to "see" these labels in some other way...

**Comment by kencochrane** [comment]
OK thanks for the feedback. I'll add it to the list.

**Comment by kacole2** [comment]
seeing as how this request has been added to the beta, i'm closing the issue.
