### ISSUE TITLE
FR: preinstalled git

### ISSUE THREAD

**Issue by d-h1** [docker/for-aws#63]
The image should come with git preinstalled

**Comment by kencochrane** [comment]
we try and keep the image sizes down, and only install what is required. You can install it on your own with the following command once you login to one of the managers.

```
sudo apk update && apk add git
```

**Comment by d-h1** [comment]
justin from #docker-for-aws told me to add this issue...

**Comment by kencochrane** [comment]
@leostarcevic yes, thank you, and we will work on adding it in a future version. I wanted to give you a way to use it now, so you aren't blocked.

**Comment by d-h1** [comment]
Great! keep up the good work! If I understood it right i can add it myself with linuxkit, upload to s3 and use it in the template?

**Comment by kencochrane** [comment]
We are not using linuxkit yet, we are using it's predecessor, but are in the process of converting over to linuxkit. 

Right now, you can add git by logging into a manager and running the command that I listed above, that will get it to you.

If you let me know what you are trying to do, I might be able to give you the best option available.

**Comment by friism** [comment]
Also: https://github.com/linuxkit/linuxkit/pull/2201#issuecomment-315246363

**Comment by d-h1** [comment]
closing this! I installed everything I needed in a container instead, by mounting docker.sock I could run all steps to get my services up and running on the "host"...
