### ISSUE TITLE
CloudStor for AWS

### ISSUE THREAD

**Issue by jicowan** [docker/for-aws#65]
### Mount an EFS volume to a particular container instead of a service

Is there a way to use the CloudStor plugin for AWS to mount an EFS volume to a particular container?

**Comment by ddebroy** [comment]
@jicowan Yes you can certainly create a regular docker volume and mount it into a container. As mentioned in https://docs.docker.com/docker-for-aws/persistent-data-volumes/#share-the-same-volume-among-tasks-using-efs

1. Make sure when you create the swarm through CFN, you select `yes` for `Create EFS prerequsities for CloudStor?`

2. You can create the volume, say `mysharedvol2` with a command like:
```
docker volume create -d "cloudstor:aws" --opt backing=shared mysharedvol2
```
3. You can mount the volume in any container anywhere in your swarm with `-v`. For example, to mount the `mysharedvol2` from above at `/mydata` within a basic `alpine` container, you can do:
```
docker run -ti -v mysharedvol2:/mydata alpine /bin/sh
```

**Comment by ddebroy** [comment]
If there is an issue, please re-open this bug. Otherwise a question like this should be posted on the forum: https://forums.docker.com/c/docker-for-aws or the Slack channel.

Closing for now.
