### ISSUE TITLE
Can't create volume with cloustor - "Invalid volume size" error

### ISSUE THREAD

**Issue by OmpahDev** [docker/for-aws#67]
### Expected behavior
docker volume create -d "cloudstor:aws" testvolume would create a cloudstor volume named "testvolume"

### Actual behavior
Fails to create, with error: 
`Error response from daemon: create testvolume: VolumeDriver.Create: volume creation failed: Invalid volume size: strconv.ParseInt: parsing "": invalid syntax`

### Information
Docker for AWS version: Docker CE for AWS 17.06.0-ce (17.06.0-ce-aws2)

If I attempt to create the volume using docker stack deploy, running docker inspect on the service requesting the volume yields the same error:
```
        "Status": {
            "Timestamp": "2017-07-18T16:47:30.963094086Z",
            "State": "rejected",
            "Message": "preparing",
            "Err": "create test_testvolume: VolumeDriver.Create: volume creation failed: Invalid volume size: strconv.ParseInt: parsing \"\": invalid syntax",
            "ContainerStatus": {},
            "PortStatus": {}
        },

**Comment by FrenchBen** [comment]
Please see the documentation:
https://docs.docker.com/docker-for-aws/persistent-data-volumes/#use-a-unique-volume-per-task-using-ebs
When using EBS backed volumes, a size needs to be specified.

**Comment by friism** [comment]
We should improve the error message if possible
-- 
http://friism.com/
(650) 318-1051
Sapere aude
