### ISSUE TITLE
Add support for HTTP Listeners / Proxy Protocol

### ISSUE THREAD

**Issue by saarons** [docker/for-aws#68]
### Expected behavior
Expected to be able to determine source IP address from inside the swarm.
### Actual behavior
Wasn't able to determine source IP address.
### Information
By default all the backend listeners on the ELB are configured in TCP mode which by default doesn't contain the original source IP. What can be done is enable the Proxy Protocol described here: http://docs.aws.amazon.com/elasticloadbalancing/latest/classic/enable-proxy-protocol.html. I was hoping we could do something similar to the ACM certificate label:
```
docker service create --label com.docker.aws.lb.proxy="true"
```

The alternative is that we use a similar syntax to change the listener type to something like HTTP so that downstream services get things like the `X-Forwarded-For` header automatically.

**Comment by FrenchBen** [comment]
This isn't exactly the same, but could be considered a dup of https://github.com/moby/moby/issues/25526

The solution provided here isn't ideal, but seems to work:
https://github.com/moby/moby/issues/25526#issuecomment-275292393

**Comment by saarons** [comment]
@FrenchBen I don't think it's exactly the same issue. I actually tried something similar to that and the problem is the ELB didn't create any forwarding rules, so I'd have to point everything to the nodes directly. And that requires modifying a bunch more stuff to allow direct access.

**Comment by kencochrane** [comment]
I'm thinking that it is probably best to allow someone to decide if they want the protocol to be SSL (TCP) or HTTPS. The most common use case is for people to use this for load balancing HTTP traffic, and the X-forwarded-for header is far more common then parsing proxy protocols. 

I just need to figure out the best approach. Just spit balling here, but maybe something like this.

```
--label com.docker.aws.lb.arn="arn:aws:acm:us-east 1:0123:certificate/c02-117-b6@HTTPS:444"
```

We default to SSL (TCP) but if you add HTTPS: before the port then you can change to HTTPS protocol.

Just an idea, would that work?

**Comment by saarons** [comment]
@kencochrane Yes that would work out very well. We could even use the same syntax to support HTTP since I imagine a fair bit of people would like the option to choose between HTTP/HTTP for the back-end protocol.

**Comment by kencochrane** [comment]
@saarons by default when you use SSL (TCP) it uses TCP in the backend protocol, and HTTPS goes to HTTP in backend. 

Are you asking to also configure the backend protocol so it could be HTTPS into ELB and then HTTPS to the backend instance, so SSL/TLS all the way through?

**Comment by saarons** [comment]
@kencochrane Whoops, my bad I think I was too confusing.

I am asking for HTTPS->ELB->HTTP. I think it's described by the second row of the HTTP/HTTPS Load Balancer table here: http://docs.aws.amazon.com/elasticloadbalancing/latest/classic/using-elb-listenerconfig-quickref.html. There might be demand for HTTPS->ELB->HTTPS (third row of that table) but I think that's probably not as important.

**Comment by kencochrane** [comment]
@saarons ok, gotcha, that is what I was thinking as well. I won't add the HTTPS->ELB->HTTPS right now, we can add in future if there are lots of requests.

**Comment by RehanSaeed** [comment]
Would the AWS Application Load Balancer (ELB v2) solve this problem https://github.com/docker/for-aws/issues/83?

**Comment by kencochrane** [comment]
This will be available in 17.07

**Comment by andrh** [comment]
Does this mean that we will also be able to specify HTTP as the listener protocol?

**Comment by FrenchBen** [comment]
@andrh if it's not working, feel free to contribute to it here:
https://github.com/docker/infrakit/tree/master/pkg/provider/aws/plugin/loadbalancer

**Comment by 4s4g4** [comment]
> I'm thinking that it is probably best to allow someone to decide if they want the protocol to be SSL (TCP) or HTTPS. The most common use case is for people to use this for load balancing HTTP traffic, and the X-forwarded-for header is far more common then parsing proxy protocols.
> 
> I just need to figure out the best approach. Just spit balling here, but maybe something like this.
> 
> --label com.docker.aws.lb.arn="arn:aws:acm:us-east 1:0123:certificate/c02-117-b6@HTTPS:444"
> 
> We default to SSL (TCP) but if you add HTTPS: before the port then you can change to HTTPS protocol.
> 
> Just an idea, would that work?

@kencochrane But enabling support for PROXY protocol on ELB following [https://docs.aws.amazon.com/elasticloadbalancing/latest/classic/enable-proxy-protocol.html](https://docs.aws.amazon.com/elasticloadbalancing/latest/classic/enable-proxy-protocol.html) can cause some damage to Docker For AWS ? Is the PROXY support will be disabled if docker/swarm change something in ELB ?

> Can I manually change the ELB configuration?
> No. If you make any manual changes to the ELB, they are removed the next time we update the ELB configuration based on any swarm changes. This is because the swarm service configuration is the source of record for service ports. If you add listeners to the ELB manually, they could conflict with what is in swarm, and cause issues.

[https://docs.docker.com/docker-for-aws/load-balancer/](https://docs.docker.com/docker-for-aws/load-balancer/)

**Comment by jboettcher1** [comment]
Is there a way to set SSL for the backend/instance protocol? I am trying to do end-to-end encryption and want something like SSL:443 -> ELB -> SSL:443. I can configure the LB (classic) protocol/port and the instance port but not the instance protocol. It always gets set to TCP.
