### ISSUE TITLE
Cannot connect (http) to container with swarm mode and host port exposed 

### ISSUE THREAD

**Issue by datacarl** [docker/for-aws#7]
### Expected behavior
Starting a service in swarm mode with `--publish mode=host` and sshing to the node the service is running on, I should be able to `curl localhost:<port>` and get a response from the web server in the container.

### Actual behavior
```
curl localhost:8080
curl: (7) Failed to connect to localhost port 8080: Connection refused
```

I *can* curl the container from another swarm manager node though, e.g. `curl ip-172-31-2-207.us-west-2.compute.internal:8080`.

I assume this is b/c you end up in a `shell` container when sshing to the nodes and that container lacks some config/permissions to curl the containers on the host.

### Information

Diagnostics session id: 1486980459-QFk83ULpnQE201EeuoSqPFJwpc6YhUN9

### Steps to reproduce the behavior

Spin up docker for aws latest release. 

ssh to a manager node and run
```
docker service create \
  --name=myservice \
  --publish mode=host,target=80,published=8080,protocol=tcp \
  nginx:alpine
```

ssh to the node the container is running on and run
`curl localhost:8080`

**Comment by FrenchBen** [comment]
Your assumption is correct, since you ssh into a shell container, you cannot use `localhost`. 
However you can use `docker0`:
```bash
Welcome to Docker!
~ $ docker service create \
>   --name=myservice \
>   --publish mode=host,target=80,published=8080,protocol=tcp \
>   nginx:alpine
kxwwhjuosy63nekbdrbv3f5qp
~ $ docker service ps myservice
ID            NAME         IMAGE         NODE                                         DESIRED STATE  CURRENT STATE          ERROR  PORTS
amklip8erigv  myservice.1  nginx:alpine  ip-172-31-37-249.us-west-2.compute.internal  Running        Running 2 seconds ago         *:8080->80/tcp
~ $ ssh ip-172-31-37-249.us-west-2.compute.internal
~ $ curl 172.17.0.1:8080
<!DOCTYPE html>
<html>
<head>
<title>Welcome to nginx!</title>
<style>
    body {
        width: 35em;
        margin: 0 auto;
        font-family: Tahoma, Verdana, Arial, sans-serif;
    }
</style>
</head>
<body>
<h1>Welcome to nginx!</h1>
<p>If you see this page, the nginx web server is successfully installed and
working. Further configuration is required.</p>

<p>For online documentation and support please refer to
<a href="http://nginx.org/">nginx.org</a>.<br/>
Commercial support is available at
<a href="http://nginx.com/">nginx.com</a>.</p>

<p><em>Thank you for using nginx.</em></p>
</body>
</html>
~ $ 
```

**Comment by datacarl** [comment]
👍  thx for the quick reply
