### ISSUE TITLE
"invalid mount config for type "bind": bind source path does not exist"

### ISSUE THREAD

**Issue by Deepak-Vohra** [docker/for-aws#74]
### Expected behavior
Service gets created using a bind mount.

### Actual behavior
Service does not get created and the following error message is generated:
`"invalid mount config for type "bind": bind source path does not exist"`

### Information
```
~ $ docker --version
Docker version 17.06.0-ce, build 02c1d87
```
```
~ $ docker info
Containers: 5
 Running: 4
 Paused: 0
 Stopped: 1
Images: 8
Server Version: 17.06.0-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: awslogs
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host ipvlan macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: active
 NodeID: o0h7o09a61ico7n1t8ooe281g
 Is Manager: true
 ClusterID: y20lilgtj80ezqawscmr5a79x
 Managers: 1
 Nodes: 5
```

  - Full output of the diagnostics from "docker-diagnose" ran from one of the instance
  - A reproducible case if this is a bug, Dockerfiles FTW
  - Page URL if this is a docs issue or the name of a man page

### Steps to reproduce the behavior

  1. Create a Docker for AWS Swarm (eg. 1 manager 2 worker nodes)
  2. Login into each Swarm instance and create a directory on each host for the bind mount.
`sudo mkdir -p /etc/mysql/scripts`
3. Create a service with the bind mount.

```
docker service create \
   --env MYSQL_ROOT_PASSWORD='mysql' \
   --replicas 1 \
  --mount type=bind,src="/etc/mysql/scripts",dst="/scripts" \
  --name mysql \
      mysql

```

Service does not get created.

**Comment by kencochrane** [comment]
1. When you ssh into the host, you are sshing into a container. 
2. When you run mkdir -p /etc/mysql/scripts you are doing that inside of the container, not directly on the host.
3. When you create a service with a bind mount, the mount comes from the host. Since /etc/mysql/scripts was created into the ssh container, instead of the host, the mount directory might not be what you expect.

When the service doesn't get created, is there an error that it throws, if so, what is the error?

**Comment by Deepak-Vohra** [comment]
Reposting from moby/moby.

```
~ $ docker service ps --no-trunc mysql
ID                          NAME                IMAGE                                                                                  NODE                            DESIRED STATE       CURRENT STATE             ERROR                                                                     PORTS
x4k047clllkskm4j1uteeqm27   mysql.1             mysql:latest@sha256:75c563c474f1adc149978011fedfe2e6670483d133b22b07ee32789b626f8de3   ip-172-31-16-11.ec2.internal    Ready               Rejected 2 seconds ago    "invalid mount config for type "bind": bind source path does not exist"   
u3edkaozfnuakfj1a0qn9wth5    \_ mysql.1         mysql:latest@sha256:75c563c474f1adc149978011fedfe2e6670483d133b22b07ee32789b626f8de3   ip-172-31-16-11.ec2.internal    Shutdown            Rejected 7 seconds ago    "invalid mount config for type "bind": bind source path does not exist"   
q6zqonfae1csnlzeaxbvuu3lk    \_ mysql.1         mysql:latest@sha256:75c563c474f1adc149978011fedfe2e6670483d133b22b07ee32789b626f8de3   ip-172-31-16-11.ec2.internal    Shutdown            Rejected 12 seconds ago   "invalid mount config for type "bind": bind source path does not exist"   
1mo10gigap8j7rik6bx97nk2h    \_ mysql.1         mysql:latest@sha256:75c563c474f1adc149978011fedfe2e6670483d133b22b07ee32789b626f8de3   ip-172-31-35-209.ec2.internal   Shutdown            Rejected 17 seconds ago   "invalid mount config for type "bind": bind source path does not exist"   
b2iupkrkg20jsra9dld45gdid    \_ mysql.1         mysql:latest@sha256:75c563c474f1adc149978011fedfe2e6670483d133b22b07ee32789b626f8de3   ip-172-31-35-209.ec2.internal   Shutdown            Rejected 22 seconds ago   "invalid mount config for type "bind": bind source path does not exist"   
```

**Comment by kencochrane** [comment]
@dvohra yeah, it is what I thought. "invalid mount config for type "bind": bind source path does not exist". Because you created the directory in the ssh container, it isn't available on the host, which is where it is looking for that directory when the service starts up.

To create the directory, you will need to do something like this.

```
docker run -it -v /:/myroot alpine /bin/sh -c "mkdir -p /myroot/etc/mysql/scripts/"
```
This will mount the host / filesytem into the container at /myroot, it will then mkdir the "/etc/mysql/scripts" directory on the host filesystem, which will allow you to run your service command that you have above.

**Comment by Deepak-Vohra** [comment]
Thanks @kencochrane.  Docker for AWS does not provide access to the host by default. Does accessing the root directory on the host within the set of features the managed service  provides? Usually managed services don't expect access to the host and directories being created on the host.

**Comment by Deepak-Vohra** [comment]
The purpose of a `bind` mount is to access pre-existing directories on the host. Typically, the host directories are created and files added to the directories before creating a service. And not be creating the directory when creating the service. Also, goes against the objective of a managed service which is provision all the required resources in a graphical user interface (GUI). A suitable feature would be to add a field in the managed service GUI to add directories and upload files.

**Comment by kencochrane** [comment]
@dvohra have you looked into [cloudstor](https://docs.docker.com/docker-for-aws/persistent-data-volumes/) or [data volumes](https://docs.docker.com/engine/tutorials/dockervolumes/#remove-volumes)?

**Comment by Deepak-Vohra** [comment]
Thanks @kencochrane. data volumes are not for Docker Swarm mode and the `bind` mount issue is still not fixed. cloudstor is an alternative but still not for the `bind` mount.

**Comment by hierozbosch** [comment]
Same issue: invalid mount config for type "bind": bind source path does not exist.  @kencochrane, I ssh'ed onto the db node--from your explanation I guess I'm now inside a container on that node.  So I tried to create a directory in the node's root, outside the container, based on your example:
 `docker run -it -v /:/myroot alpine /bin/sh -c "mkdir -p /myroot/neo_data"`,   I could then `ls /` and there's my neo_data directory, but when I deploy the stack from the manager, my db service throws the same "path does not exist" error.  Does the docker command above address the daemon on the host, allowing it to create a directory on the host's root outside the container, or is it talking to a docker daemon running inside the ssh container?  Thanks.

**Comment by FrenchBen** [comment]
@hierozbosch When you deploy it as a service, it will deploy it to any node - Unless you restrict your service to deploy the task only on the node that has the folder `neo_data` created, it's not going to work. 
See: https://docs.docker.com/engine/reference/commandline/service_create/#specify-service-constraints-constraint

**Comment by shazChaudhry** [comment]
I had the same issue on 'Docker for AWS' and managed to get round it by using `docker config create` instead. 
- you can take a look at an example at: https://docs.docker.com/engine/swarm/configs/#configure-the-nginx-container
- If you are using a compose file to stand up docker swarm mode services then you may be interested in taking a look at: https://docs.docker.com/compose/compose-file/#short-syntax

**Comment by withattribution** [comment]
@shazChaudhry using docker config super helped getting init scripts to postgres container in Docker for AWS. Mega thanks!
