### ISSUE TITLE
x509: certificate signed by unknown authority

### ISSUE THREAD

**Issue by galindro** [docker/for-aws#75]
I'm trying to pull images from my custom docker registry but I can't because it is using a self signed certificate:
```bash
docker: Error response from daemon: Get https://r.sb/v2/: x509: certificate signed by unknown authority.
```
So, I've tried to add the certificate to the O.S. root ca chain, but a warning message is displayed when I run the command update-ca-certificates:

```bash
~ # openssl s_client -connect r.sb:443 -showcerts </dev/null 2>/dev/null | openssl x509 -outform PEM | sudo tee /usr/local/share/ca-certificates/cert-sb.crt
~ # update-ca-certificates
WARNING: ca-certificates.crt does not contain exactly one certificate or CRL: skipping
```
After that I've tried to restart docker service to read the root ca, but I can't. It seems that command `rc-service` doesn't exists. How userdata could use it to restart docker?
```bash
~ # rc-service docker restart
-ash: rc-service: not found
```
So, I decided to reboot the server, but I still can't pull docker image from it. The same certificate error occurs. Why?

**Comment by FrenchBen** [comment]
Depending on the version of Docker for AWS, it may not persist your changes to the daemon configs or certificate. The machines are treated as cattle and thus only persist a few items.
There's a patch in flight to allow for daemon settings to persist after a reboot. 

Regarding a simple update to the docker config, you need to do this at a privileged level. 
```
$ docker run --rm -it --privileged --pid host justincormack/nsenter1
```
This will give you access to the `rc-service`, but keep in mind that this will kill the current containers, and thus probably log you out. 
Additionally an improperly configured daemon will break your existing setup and may trigger a node replacement.

**Comment by galindro** [comment]
@FrenchBen I'm not using Docker for AWS Cloudfront template. I'm just started an instance from the ami used by the template in us-east-1 region:

![image](https://user-images.githubusercontent.com/4622097/28568270-9b8a83f0-710b-11e7-8b32-1fa24a1f3f06.png)

I'll not make use of Docker for AWS because it makes my infrastructure very expensive because it not uses spot instances and not uses route53 auto instances registration (like ranches does). It depends on a load balancer.

After furter reading in this project issues, I've noticed that when I login into the instance, I'm not effectively logging into the host, but, into a ssh container. This is why I haven't access to host console, thus, I can't access many host binaries

After executing the container that I've mentioned, I could access the host shell, but `update-ca-certificates` is displaying the same warning. So, IMHO, the certificate problem isn't related to the persistence itself. It is related to the way that ca-certificates are installed on Alpine (Moby Linux in this case). If it is related to persistence, I should at least be able to make it work before instance restart.

Am I wrong? How could I make it work?

```bash
/ # openssl s_client -connect r.sb:443 -showcerts </dev/null 2>/dev/null | openssl x509 -outform PEM | tee /usr/local/share/ca-certificates/cert-sb.crt
-----BEGIN CERTIFICATE-----
MIIDljCCAn4CCQDnpR2m5U17pTANBgkqhkiG9w0BAQsFADCBjDELMAkGA1UEBhMC
QlIxCzAJBgNVBAgMAlNDMRMwEQYDVQQKDApTb2NpYWxiYXNlMRYwFAYDVQQHDA1G
bG9yaWFub3BvbGlzMQ0wCwYDVQQDDAQqLnNiMQswCQYDVQQLDAJJVDEnMCUGCSqG
SIb3DQEJARYYZGV2b3BzQHNvY2lhbGJhc2UuY29tLmJyMB4XDTE3MDUyNDIyMTQ1
MloXDTI3MDUyMjIyMTQ1MlowgYwxCzAJBgNVBAYTAkJSMQswCQYDVQQIDAJTQzET
MBEGA1UECgwKU29jaWFsYmFzZTEWMBQGA1UEBwwNRmxvcmlhbm9wb2xpczENMAsG
A1UEAwwEKi5zYjELMAkGA1UECwwCSVQxJzAlBgkqhkiG9w0BCQEWGGRldm9wc0Bz
b2NpYWxiYXNlLmNvbS5icjCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEB
ANX8/G/JvQxiRX7z7shVYy1ecLG4NM/ISGtNWKlhWtPk8dE/ogBodandWttvXvhK
sgi0FSCtxpK7V1QbjcKbN+9cZwNf+lFWxhlwHqHnBXL3xPlhWdrB4cZ2W+QnR1jh
YMYyCuLwKQw6t7YX0oxxNHJPPdNXUw9M0U9/j60RrHrcDGrmcv1elpOYyWgxapn9
bYepYfc75RHFpYn/egBSDTNZvdhjz1FlG/hUed/vYYi2d7ih98wo0sAMg8fuojvI
ylKgLhMKcRKtJ8kEByNhx5fRhsfM80SJZ45vKlJgpcoQO5M2yHjzZpPcRAWvUZc1
ApyWkksoEsUXOj+6qYQeIRsCAwEAATANBgkqhkiG9w0BAQsFAAOCAQEAjkBfoQLI
ELC0nmPN54bWOlq6ZcSgaj8d8a8IOPeu1kCznakFmN4Sw8vhVvXkaq3ABLYrOq42
8h0b3tSO0O2JuECi4mmjRMCIfE3Ytq0IlRui4T7eLcof54UlFB34LY0ciO0c7KbQ
xURPOPn7vMIIga8ARwQWvd94mUWFQW0pvWX4Hwto6Ccb8DoMAy24muIv1i6OS7To
0Gb8ozmHN3BzITI5340R+vtpH0pC5CkJ/CRwLA6WPzK/ZDRc2MjrZP7EDGR5X3eq
dVGlUBTajltGCFlMMiNvIZ/I5i6CPsHuH5D4kNcO/MdGJkf3JrpbYtfT4fZM8b3m
JFROE70mQl/OWw==
-----END CERTIFICATE-----

/ # ls -lh /usr/local/share/ca-certificates/cert-sb.crt
-rw-r--r--    1 root     root        1.3K Jul 25 10:21 /usr/local/share/ca-certificates/cert-sb.crt

/ # update-ca-certificates
WARNING: ca-certificates.crt does not contain exactly one certificate or CRL: skipping

/ # cat /etc/issue 

Welcome to Moby

                        ##         .
                  ## ## ##        ==
               ## ## ## ## ##    ===
           /"""""""""""""""""\___/ ===
      ~~~ {~~ ~~~~ ~~~ ~~~~ ~~~ ~ /  ===- ~~~
           \______ o           __/
             \    \         __/
              \____\_______/

/ # uname -a
Linux 74d44f778cef 4.9.36-moby #1 SMP Tue Jul 11 02:00:07 UTC 2017 x86_64 Linux

/ # cat /etc/alpine-release 
3.5.0
```

**Comment by galindro** [comment]
@FrenchBen , I've made it working now after this procedure:

1. Login into instance
2. Execute the following container to gain access to host shell:
```bash
docker run --rm -it --privileged --pid host justincormack/nsenter1
```
3. Create this directory tree (replace r.sb by the registry fqdn with port if applied):
```bash
mkdir -p /var/etc/docker/certs.d/r.sb/
```
4. Create 3 files inside of it.
**client.cert** will be the registry certificate
**ca.crt** will be a copy of client.cert if your registry certificate is self-signed
**client.key** will be the registry certificate private key
```bash
/ # ls -lh /var/etc/docker/certs.d/r.sb/
total 12
-rw-r--r--    1 root     root        1.3K Jul 25 10:57 ca.crt
-rw-r--r--    1 root     root        1.3K Jul 25 10:56 client.cert
-rw-r--r--    1 root     root        1.6K Jul 25 10:56 client.key
```
5. After create those files, I could successfully access my private registry, even after instance reboot.

----------------------------
Checking the instance persistence, you are right @FrenchBen. / is mounted as a tmpfs filesystem. The only persistent filesystem is /var:

```bash
/ # df -h
Filesystem                Size      Used Available Use% Mounted on
tmpfs                   495.5M    161.2M    334.2M  33% /
tmpfs                    99.1M    320.0K     98.8M   0% /run
cgroup_root              10.0M         0     10.0M   0% /sys/fs/cgroup
dev                      10.0M         0     10.0M   0% /dev
shm                     495.5M         0    495.5M   0% /dev/shm
/dev/xvdb1               19.7G    512.7M     18.2G   3% /var
tmpfs                    99.1M         0     99.1M   0% /tmp
tmpfs                   495.5M     12.0K    495.4M   0% /Database
/dev/xvdb1               19.7G    512.7M     18.2G   3% /var/lib/docker/overlay2
overlay                  19.7G    512.7M     18.2G   3% /var/lib/docker/overlay2/d656319a9bc4a365ae8d49a32f13f2208de63e594cbf63d0d5d4767284bd8936/merged
shm                      64.0M         0     64.0M   0% /var/lib/docker/containers/3a5e678450588404558efa0b0ce2940adededf520a832048f2446894990deb5a/shm
overlay                  19.7G    512.7M     18.2G   3% /var/lib/docker/overlay2/c74a4eb84fa8619f5e7260a54fa7ea7be81dd8e7f6dd42387eb6b749f59ddc07/merged
shm                      64.0M         0     64.0M   0% /var/lib/docker/containers/1fcc5bf9b96b6119fd2abda8f7fdcb0e9b471c846f59032dd0a12667e2663523/shm
```

This explains why files created inside ssh container persists after instance reboot.

Docker team should document this ASAP. I've lost my last day searching about it and trying to make it work. If it had been documented, maybe I would not have wasted so much time.

Thanks for your help.

**Comment by FrenchBen** [comment]
@galindro thanks for sharing the steps to make this work; as you mentioned you are in an SSH container which means that changes will not persist; only privileged mode will allow you to modify the host. 
Your case is a bit specific as you are using our AMI as a single instance, outside of our template. 
In Docker for AWS we treat instances as cattle and thus don't expect data to remain. 

For the above reason we don't recommend writing anything to the host; we're happy to share the information on specific cases, but documenting it would lead people to think it's persistent, when it's not.

**Comment by galindro** [comment]
IMHO, Docker team must think about It and try to create an API or something similar to make possible persist things like this into the O.S. 
I'm sure that my case isn't unique in the world. 

If it isn't possible, explain it into the docs. Show how filesystem is mounted, how the SSH to the instance works, etc... This isn't documented.
