### ISSUE TITLE
Add output for ELB's DNS Zone ID

### ISSUE THREAD

**Issue by hairyhenderson** [docker/for-aws#8]
### Expected behavior

It'd be useful to have an additional output from the CFN template so that I can automate creation of records in Route53 pointing to the ELB.

### Information

So far I've been doing it myself with this little script:

```bash
#!/bin/bash
url=https://editions-us-east-1.s3.amazonaws.com/aws/edge/Docker.tmpl
jq_script='
.Outputs += { "ELBDNSZoneID": {
  "Description": "Use this zone ID to update your DNS records",
  "Value": { "Fn::GetAtt": [ "ExternalLoadBalancer", "CanonicalHostedZoneNameID" ] }
} }'
curl -sSL $url | jq "$jq_script" > Docker.tmpl
```

But it'd be nice not to have to patch the template myself 😁 

Just for some additional context, I'm using Terraform to deploy D4AWS, and I tack on a DNS entry with a resource like this:

```hcl
resource "aws_route53_record" "friendly_name" {
  zone_id = "my_zone_id"
  name = "myd4aws.example.com"
  type = "A"

  alias {
    name = "${aws_cloudformation_stack.docker4aws.outputs["DefaultDNSTarget"]}"
    zone_id = "${aws_cloudformation_stack.docker4aws.outputs["ELBDNSZoneID"]}"
    evaluate_target_health = true
  }
}
```

**Comment by hairyhenderson** [comment]
Hi @kencochrane - was this implemented? Or is there some other reason this was closed? Thanks!

**Comment by kencochrane** [comment]
Sorry it was implemented in my internal alpha version (available in next beta) and this issue was linked to my PR and was closed automatically when merged, I'll reopen

**Comment by hairyhenderson** [comment]
@kencochrane no problem - don't mind if it's closed, so long as it's not forgotten - maybe could label it with `status/3-fixed` (as per the `README`)?

**Comment by hairyhenderson** [comment]
🎉 thanks @kencochrane
