### ISSUE TITLE
Support encryption at rest for EFS volumes

### ISSUE THREAD

**Issue by seriousben** [docker/for-aws#90]
### Information

AWS just release support for encryption at rest for EFS. https://aws.amazon.com/about-aws/whats-new/2017/08/amazon-efs-now-supports-encryption-of-data-at-rest/

The cloudformation stack needs to be changed to allow toggling encryption at rest.

**Comment by FrenchBen** [comment]
@seriousben To help us make this happen, can you provide the changes needed to the cloudformation and see how well it works on your end?

**Comment by seriousben** [comment]
@FrenchBen Sounds good. We'll be implementing this within a few sprints here and as usual as soon as we do we'll share our sed / jq scripts.

**Comment by seriousben** [comment]
We are finally starting on this now. After an initial look, it seems the approach we will take is to let d4aws support custom EFS filesystem ids created outside of cloudformation.

Does that seem an acceptable approach to this? Gives us a way to use an existing EFS filesystem + gives us a way to get encryption.

**Comment by netflash** [comment]
Looks like 17.12 introduced that parameter

**Comment by FrenchBen** [comment]
Closing as added to 17.12
