### ISSUE TITLE
How Does Cloudstor with EBS Volumes Work?

### ISSUE THREAD

**Issue by RehanSaeed** [docker/for-aws#91]
### Expected behavior

I expected to see an EBS volume in AWS with the name I gave in my docker-stack.yml file.

### Actual behavior

The volume has no name, just an ID.

### Information

If I wanted to move an EBS volume to a different docker service or even a different swarm cluster, how could this be achieved? How does Cloudstor match the volume name in my docker-stack.yml file to the EBS volume?

**Comment by FrenchBen** [comment]
![](https://media.giphy.com/media/ujUdrdpX7Ok5W/giphy.gif)

There's a bit of information within our docs:
https://docs.docker.com/docker-for-aws/persistent-data-volumes/

@ddebroy is the expert in that field, but if you look at the policy created `CloudstorEBSPolicy` within the template, you'll see that a policy for the volume/cluster was created. You would need to authorize the new cluster to use that existing volume. 
The "assocation" of a cluster with its EBS volumes happens using the MD5 of the StackID parameter passed down during cloudstor installation. So for a new cluster to pick up a volume from another cluster, the StackID label will need to be switched on the EBS volumes to the StackID of the new cluster

In regards to the different, the storage is associated with a `source` volume, similar to a regular docker volume. 
From the docs you can see that when you create the service, the mount source is defined as `source={{.Service.Name}}-{{.Task.Slot}}-vol` - which is the name of the volume that will be created/used.
Re-using the same source name will make the volume re-usable. The one caveat is that EBS disks cannot be attached to multiple instances at once; this means that your task would need to be scheduled on the same instance as the one that created the volume to begin with.

**Comment by ddebroy** [comment]
@RehanSaeed each EBS volume created by Cloudstor has a label `CloudstorVolumeName` which will reflect the name passed down to Cloudstor by Docker engine. We do not populate the `Name` tag as that is often used by our users for their own tracking purposes as well as by the EBS GUI in AWS for display purposes. You can set the `Name` tag for a EBS volume created through cloudstor by specifying it as `--opt ebs_tag_Name=AnyVolName`. So if you want to enumerate the list of volumes created by Cloudstor, query for all volumes with the `CloudstorVolumeName` label and you will find their docker assigned names there.

If you need to share the EBS volume across services, you can potentially skip the `{{Service.Name}}` bit in the templatized naming and only use the `{{.Task.Slot}}`. As mentioned above, please always make sure (either using node constraints or some other mechanism) that no two tasks (from the same or different services) are mounting the same volume at the same time - that will lead to IO failures and potentially corruptions.

**Comment by RehanSaeed** [comment]
Where can I retrieve the StackID for a cluster apart from looking at an EBS volume?

**Comment by ddebroy** [comment]
The StackID is the AWS ARN for the stack. Please see: 

http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/using-cfn-describing-stacks.html

and

http://docs.aws.amazon.com/general/latest/gr/aws-arns-and-namespaces.html

**Comment by hrajchert** [comment]
I'm wondering the same, as I added in this stackoverflow question: https://stackoverflow.com/questions/45849116/how-does-cloudstor-relocation-work

I'm having a weird problem using docker-for-aws and cloudstor.
So I manually create 2 volumes using cloudstor like this

```
docker volume create \
  -d "cloudstor:aws" \
  --opt ebstype=gp2 \
  --opt size=15 \
  --opt iops=180 \
  --opt backing=relocatable \
  ci_ping3-1-vol

docker volume create \
  -d "cloudstor:aws" \
  --opt ebstype=gp2 \
  --opt size=15 \
  --opt iops=180 \
  --opt backing=relocatable \
  ci_ping3-2-vol
```

And I use a stack called ci to test it

```
version: "3.3"

services:
  ping3:
    image: alpine
    command: ping docker.com
    volumes:
      - ping_vol:/mydata
    deploy:
      replicas: 2
volumes:
  ping_vol:
    external:
      name: "{{.Service.Name}}-{{.Task.Slot}}-vol"
```

My swarm consist on 1 manager and 1 worker (just for testing). Then, I exec a bash inside each replica and modify a file in the `/mydata` folder. I go to the aws console and kill the working instance, forcing the service to relocate. When I look in my EBS console I can see how a second drive is created when the volume needs to move from AZ, but once the service is running again, the data inside `/mydata` is not what I was expecting.

I triend manually calling `sync` before terminating the machine, I tried to scale down to force a more graceful service termination but the result on `/mydata` is never what I expected. Weirdly enough, it seems that some times the data is filled with contents from older test... so I don't even know how to debug this :(

**Comment by friism** [comment]
@hrajchert can you open a separate issue with details?

**Comment by hrajchert** [comment]
Done, https://github.com/docker/for-aws/issues/94
sorry

**Comment by wickstargazer** [comment]
Can we reattach an EBS to the cloudstor volume in a new swarm?

**Comment by ghost** [comment]
Please copy this issue and change the title to "What is cloudstor and why do I want to use it with EBS?"

**Comment by ghost** [comment]
nevermind found one sorta https://docs.docker.com/docker-for-aws/persistent-data-volumes/

**Comment by FrenchBen** [comment]
For future discussion, please open a new issue as the original topic has been addressed.
