### ISSUE TITLE
Malformed DNS name mounting EFS with cloudstor:aws

### ISSUE THREAD

**Issue by kevin-cantwell** [docker/for-aws#98]
### Expected behavior

When installing (or enabling) `cloudstor:aws` with EFS settings, the mount should succeed.

### Actual behavior

The install fails and cannot find the unix socket.

### Information

The root cause appears to be that the mount fails due to a "bad address". I.e.: The EFS DNS name is malformed and missing the ID portion.

  - Full output of the diagnostics from "docker-diagnose" ran from one of the instance

```
docker-diagnose
OK hostname=ip-172-30-1-247-ec2-internal session=1504290592-eg2u3Ys0lQWPqERVdZdbdJU6iapUTctA
Done requesting diagnostics.
Your diagnostics session ID is 1504290592-eg2u3Ys0lQWPqERVdZdbdJU6iapUTctA
Please provide this session ID to the maintainer debugging your issue.
```
  - A reproducible case if this is a bug, Dockerfiles FTW

See steps to reproduce below.

### Steps to reproduce the behavior

  1. Create a AWS Swarm in us-east-1 using Docker Cloud (beta)
  2. `docker plugin disable cloudstor:aws`
  3. `docker plugin set cloudstor:aws EFS_SUPPORTED=1 EFS_ID_REGULAR=fs-62345b2b`
  4. `docker plugin enable cloudstor:aws`
    
    Error response from daemon: dial unix /run/docker/plugins/4a1c4c20e909f8354c08b3f92e9a14226f37e46ccfdef543e8f18521193905ec/cloudstor.sock: connect: no such file or directory

Docker logs:
```
Sep  1 18:15:37 moby root: time="2017-09-01T18:15:37Z" level=info msg="fs-62345b2b.efs.us-east-1.amazonaws.com:/ on /mnt/efs/reg type nfs4 (rw,relatime,vers=4.1,rsize=1048576,wsi
ze=1048576,namlen=255,hard,proto=tcp,timeo=600,retrans=2,sec=sys,clientaddr=172.30.1.247,local_lock=none,addr=172.30.1.176)" plugin=4a1c4c20e909f8354c08b3f92e9a14226f37e46ccfdef5
43e8f18521193905ec
Sep  1 18:15:37 moby root: time="2017-09-01T18:15:37Z" level=info msg="\" operation=mount " plugin=4a1c4c20e909f8354c08b3f92e9a14226f37e46ccfdef543e8f18521193905ec
Sep  1 18:15:37 moby root: time="2017-09-01T18:15:37Z" level=info msg="time=\"2017-09-01T18:15:37Z\" level=fatal msg=\"Could not mount: mount failed: exit status 1" plugin=4a1c4c
20e909f8354c08b3f92e9a14226f37e46ccfdef543e8f18521193905ec
Sep  1 18:15:37 moby root: time="2017-09-01T18:15:37Z" level=info msg="output=\"mount: bad address '.efs.us-east-1.amazonaws.com'\\n\"\" " plugin=4a1c4c20e909f8354c08b3f92e9a1422
6f37e46ccfdef543e8f18521193905ec
```

**Comment by ddebroy** [comment]
Can you try installing with specifying a `EFS_ID_MAXIO` parameter as well (pointing to another separate EFS ideally with MaxIO set)? Cloudstor tries to mount two EFSs during initialization - one regular and one MaxIO. Looks like it failed above when trying to mount the `EFS_ID_MAXIO` that was not provided.

**Comment by kevin-cantwell** [comment]
Both are required? That's odd, and I don't need or want to create a maxio EFS, but I'll try it and let you know.

**Comment by kevin-cantwell** [comment]
@ddebroy Setting EFS_ID_MAXIO seems to have done the trick. I just re-used the same EFS ID for both so that gets me around the problem for now. Thanks!

**Comment by ddebroy** [comment]
Great! I will make the EFS_ID_MAXIO optional to make this hack unnecessary when using in stand-alone mode. Note that reusing the same EFS for now may lead to double enumeration of volumes when doing `docker volume ls`. This can lead to various issues. I recommend using a separate EFS as AWS does not charge you unless you are storing data in it.

**Comment by kevin-cantwell** [comment]
@ddebroy Thanks. One side effect: The plugin settings don't seem to propagate to new nodes, is that a known issue? Ie: When I scale up the worker nodes the new hosts can't access the volume.

I imagine that's because the user script in the cfn template applies the default plugin settings on that node?

**Comment by ddebroy** [comment]
@kevin-cantwell The plugin settings apply only locally to the node where they are applied. The recommended way to automate this is using a tool like `swarm-exec` [https://github.com/mavenugo/swarm-exec] to install a global service that executes the commandline (`docker plugin install ...` with appropriate parameters) on each node of the swarm - event new ones when they are brought up. In our AWS CFN templates, each new node gets the necessary commandline executed as part of ASG node creation.

**Comment by kevin-cantwell** [comment]
Can you explain this a bit further please?:

> each new node gets the necessary commandline executed as part of ASG node creation

Is there a way to make sure that plugins I install get automatically applied to new nodes?

**Comment by ddebroy** [comment]
Did you use Docker Cloud to set up the swarm? Do you have the tool `swarm-exec` installed in your nodes? If so, you can make sure plugin is installed on all nodes using the commandline: `swarm-exec docker plugin install --alias cloudstor:aws --grant-all-permissions docker4x/cloudstor:17.06.1-ce-aws1 CLOUD_PLATFORM=AWS AWS_REGION=[region] AWS_STACK_ID=[any_string] EFS_SUPPORTED=1 EFS_ID_REGULAR=[EFS_REG_ID] EFS_ID_MAXIO=[EFS_MAXIO_ID] DEBUG=1`

What I was referring to above is when using the Docker4AWS CFN template @ https://docs.docker.com/docker-for-aws/ the CFN creates the EFS and the AWS ASG for the nodes is configured to always install cloudstor with the necessary parameters from the EFS creation step.

**Comment by kevin-cantwell** [comment]
Ok just to be clear: `swarm-exec` will execute the docker command across every node currently in the swarm, but _not_ on new nodes that come up in the future. Correct?

**Comment by kevin-cantwell** [comment]
I think I understand. Thanks. Feel free to close this issue.
